In [3]:
# https://github.com/jkobject/JKBIO
# JKBio repo commit: 912087536d3cf6a7f1cbb00f9b131bc645780ee9 (9120875)
from __future__ import print_function
import os.path
import dalmatian as dm
import pandas as pd
import sys

pathtoJK_parent = "../depmap_omics/"
sys.path.append(pathtoJK_parent)
from mgenepy import terra
from mgenepy.utils import *
from src.helper import *

import numpy as np
from gsheets import Sheets

%load_ext autoreload
%autoreload 2

"""
To generate the required files to read in from Google sheets:
Log into the Google Developers Console with the Google account whose spreadsheets you want to access.
Create (or select) a project and enable the Drive API and Sheets API (under Google Apps APIs).

https://console.developers.google.com/

Go to the Credentials for your project and create New credentials > OAuth client ID > of type Other.
In the list of your OAuth 2.0 client IDs click Download JSON for the Client ID you just created.
Save the file as client_secrets.json in your home directory (user directory).
Another file, named storage.json in this example, will be created after successful authorization
to cache OAuth data.

On you first usage of gsheets with this file (holding the client secrets),
your webbrowser will be opened, asking you to log in with your Google account to authorize
this client read access to all its Google Drive files and Google Sheets.
"""
sheets = Sheets.from_files('~/.client_secret.json', '~/.storage.json')
replace = {'T': 'Tumor', 'N': 'Normal', 'm': 'Unknown', 'L': 'Unknown'}

# CCLF TWIST Pipeline

*go to the [readme](./README.md) to see more about execution*


This pipeline has the following major steps:
1. Pull in information about the TWIST batch(es) from Google sheet(s).
2. Create a TSV of the new sample information
3. Create a TSV of the new sample set information (e.g. cohorts)
4. Upload the sample information and sample set TSVs to the Terra workspace 
5. Run Terra workflows to get copy number (CNV) and mutation (SNV) information, and to create copy number heat maps by batch and by cohort.

# Initialization
Pull in information about the TWIST batch(es) from Google sheet(s).

**Note:** Each time, the `samplesetnames` and the `gsheeturllist` need to be updated.

In [4]:
# create sample set names for each batch in *chronological* order (e.g. CCLF_TWIST1 before CCLF_TWIST2)
# if you only have one batch to run, still make it a list e.g. ["CCLF_TWIST1"]
# this ensures that the pipeline will run as designed
samplesetnames = ['CCLF_TWIST65']


# list of the external sheets produced for each batch you want to run through the pipeline
# TO EDIT:
gsheeturllist = ['https://docs.google.com/spreadsheets/d/1K2rWwE4XeO-YJDGoMOmf3J-8hieSV99mzxeciW-kRXQ/edit?gid=0#gid=0']

# generate the sample set names we will use in Terra
samplesetnames_normals = [s + '_normals' for s in samplesetnames]
samplesetnames_tumors = [s + '_tumors' for s in samplesetnames]
samplesetnames_pairs = [s + '_pairs' for s in samplesetnames]
samplesetnames_all = [s + '_all' for s in samplesetnames]

# workspace where we are pulling in the data from
data_workspace="cancer-delivery/Cancer_Cell_Line_Factory_CCLF_PanCancer_PanelSeq_DRAGEN"

# workspace where we are running the workflows
proc_workspace="nci-mimoun-bi-org/PANCAN_TWIST copy"

# TODO: these are hard-coded in the helper.py file. However, I don't know how these columns are being used (if at all) and I think these may be meaningless.
# source="CCLF"
# picard_aggregation_type_validation="PCR"

# mapping abbreviations to full names/descriptions
cohorts2id="https://docs.google.com/spreadsheets/d/1R97pgzoX0YClGDr5nmQYQwimnKXxDBGnGzg7YPlhZJU"

# Connection errors? Reload the chunk below
For example,
`ConnectionError: ('Connection aborted.', OSError("(54, 'ECONNRESET')"))`

In [8]:
wfrom = dm.WorkspaceManager(data_workspace)
wto = dm.WorkspaceManager(proc_workspace)

# Getting the samples

- we load the samples from data workspace and load the metadata files
- we remove data that has already been processed
- we create the final ids

In [4]:
# create preliminary versions of the sample and metadata tables
newsamples, newmetadata = create_preliminary_sample_and_metadata_tables(wto, wfrom, samplesetnames, external_sheets_url_list=gsheeturllist, cohorts2id_url=cohorts2id)

Number of rows from the external ID gsheets: 48
Dropped samples: {nan}
Note that we expect to drop one per batch, the technical sequencing control.
New length after dropping any samples with no value for the Collaborator Sample ID, Sample Type, or Exported DNA SM-ID: 47
Number of samples already in Terra:  47
Number of samples remaining after filtering out samples already in the processing wm: 47
Final dimensions of the newsamples table:  (47, 31)
Final dimensions of the newmetadata table:  (47, 47)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:124: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  newmetadata = metadata.dropna(0, subset=['Collaborator Sample ID','Sample Type','Exported DNA SM-ID'])

# Creating the sample information dataframe
Create a dataframe of the new sample information

**Note:** It can be difficult to recreate the sample_info variable below after you have already uploaded TSVs to Terra since this pipeline specifically looks for samples that do not already exist in the workspace. When running the pipeline on a new batch of data, **I recommend writing the final sample_info to a file.**

**Note 2:** We replace all "/" in the External IDs with "_". This prevents errors when filepaths are created using the external IDs in Terra.

## Required metadata columns
We do not include samples that are missing information in any of the following columns in the external sheet:
- Collaborator Participant ID
- Exported DNA SM-ID
- Stock DNA SM-ID
- Participant ID <- This is the patient identifier
- Sample Type
- Original Material Type
- Material Type
- Primary Disease <- Only the technical controls won't have this information.
- Collection
- Tissue Site

Without this list of metadata, the samples will not be added to Terra.

In [6]:
# sometimes GP delivers entries that have broken bam file paths
# catch and filter out invalid entries
from google.cloud import storage

storage_client = storage.Client()
def check_broken_path(row):
    bucket_name = row['bam_file'].split("/")[2]
    file_name = "/".join(row['bam_file'].split("/")[3:])
    bucket = storage_client.bucket(bucket_name)
    return storage.Blob(bucket=bucket, name=file_name).exists(storage_client)

newsamples = newsamples[newsamples.apply(check_broken_path, axis=1)]

In [7]:
assert newmetadata.external_id_validation.is_unique, "duplicated external IDs, ask ops to rename"

In [8]:
# merge the data from the External Sheet(s) and the data from the data source (e.g. Broad genomics delivery)
df = pd.concat([newmetadata, newsamples], axis=1, sort=True)

# specify required metadata columns
tolook = ['Collaborator Participant ID','Exported DNA SM-ID', 'Stock DNA SM-ID', 'Participant ID', 'Sample Type','Tissue Site', 'Original Material Type', 'Material Type','Primary Disease', 'Collection']

In [9]:
# If any samples are missing some of the required metadata, stop now and ask the CCLF team to fill out the missing values in the External Sheet.
check_required_metadata_columns(df, tolook, cohorts2id_url=cohorts2id, drop=False)

No samples are missing any required metadata. Continue running the pipeline.

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:82: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for k, val in df['Collection'].iteritems():

,batch,Exported DNA SM-ID,Container,Position,Stock DNA SM-ID,Material Type,Volume,Conc,Participant ID,Parent Sample ID,...,participant_id,pdo,percent_mapped,reported_sex,research_project,root_sample_ids,sample_type,sequencer_model,tdr:sample_id,sample_id
SM-JKMLF,CCLF_TWIST65,SM-ONLT1,CO-37520188,D03,SM-JKMLF,DNA:DNA Genomic,62.00,2.93,PT-248HW,NaN,...,PT-248HW,PDO-50107,99.49,Female,RP-3781,[SM-JKMLF],Normal,Illumina NovaSeq 6000,SM-JKMLF,CCLF_RCRF1003-Normal-SM-JKMLF
SM-JKMLG,CCLF_TWIST65,SM-ONLTC,CO-37520188,F02,SM-JKMLG,DNA:DNA Genomic,62.00,2.43,PT-2H9KW,NaN,...,PT-2H9KW,PDO-50107,99.43,Male,RP-3781,[SM-JKMLG],Normal,Illumina NovaSeq 6000,SM-JKMLG,CCLF_cRCRF1045-Normal-SM-JKMLG
SM-JKMLH,CCLF_TWIST65,SM-ONLTH,CO-37520188,G01,SM-JKMLH,DNA:DNA Genomic,131.44,2.19,PT-2HF4C,NaN,...,PT-2HF4C,PDO-50107,99.47,Female,RP-3781,[SM-JKMLH],Normal,Illumina NovaSeq 6000,SM-JKMLH,CCLF_cRCRF1047-Normal-SM-JKMLH
SM-LYFLX,CCLF_TWIST65,SM-ONLT2,CO-37520188,D04,SM-LYFLX,DNA:DNA Somatic,508.09,2.26,PT-2DWMB,NaN,...,PT-2DWMB,PDO-50107,99.45,,RP-3781,[SM-LYFLX],Normal,Illumina NovaSeq 6000,SM-LYFLX,CCLF_RCRF1060-Normal-SM-LYFLX
SM-M1DNP,CCLF_TWIST65,SM-ONLSZ,CO-37520188,D02,SM-M1DNP,DNA:DNA Somatic,262.88,2.63,PT-28FWN,NaN,...,PT-28FWN,PDO-50107,99.53,Female,RP-3781,[SM-M1DNP],Normal,Illumina NovaSeq 6000,SM-M1DNP,CCLF_RCRF1022-Normal-SM-M1DNP
SM-N1LYI,CCLF_TWIST65,SM-ONLT3,CO-37520188,D05,SM-N1LYI,DNA:DNA Somatic,62.00,2.04,PT-3MGXR,NaN,...,PT-3MGXR,PDO-50107,99.49,Female,RP-3781,[SM-N1LYI],Normal,Illumina NovaSeq 6000,SM-N1LYI,CCLF_RCRF1189-Normal-SM-N1LYI
SM-N1LYJ,CCLF_TWIST65,SM-ONLSY,CO-37520188,D01,SM-N1LYJ,DNA:DNA Somatic,62.00,3.17,PT-3MGXT,NaN,...,PT-3MGXT,PDO-50107,99.56,Female,RP-3781,[SM-N1LYJ],Normal,Illumina NovaSeq 6000,SM-N1LYJ,CCLF_RCRF1190-Normal-SM-N1LYJ
SM-NEJCO,CCLF_TWIST65,SM-ONLTD,CO-37520188,F03,SM-NEJCO,DNA:DNA Somatic,152.52,2.19,PT-3EI5T,NaN,...,PT-3EI5T,PDO-50107,99.48,Male,RP-3781,[SM-NEJCO],Normal,Illumina NovaSeq 6000,SM-NEJCO,CCLF_NB1015-Normal-SM-NEJCO
SM-OHWXY,CCLF_TWIST65,SM-ONLSH,CO-37520188,A02,SM-OHWXY,DNA:DNA Somatic,62.00,1.83,PT-3P1PQ,NaN,...,PT-3P1PQ,PDO-50107,99.44,Male,RP-3781,[SM-OHWXY],Tumor,Illumina NovaSeq 6000,SM-OHWXY,CCLF_SJ1063-Tumor-SM-OHWXY
SM-OHWXZ,CCLF_TWIST65,SM-ONLTQ,CO-37520188,H04,SM-OHWXZ,DNA:DNA Somatic,62.00,2.18,PT-25H83,NaN,...,PT-25H83,PDO-50107,99.49,,RP-3781,[SM-OHWXZ],Tumor,Illumina NovaSeq 6000,SM-OHWXZ,CCLF_KL1081-Tumor-SM-OHWXZ
SM-OHWY2,CCLF_TWIST65,SM-ONLSK,CO-37520188,A05,SM-OHWY2,DNA:DNA Somatic,62.00,1.61,PT-3Y9US,NaN,...,PT-3Y9US,PDO-50107,99.49,Female,RP-3781,[SM-OHWY2],Tumor,Illumina NovaSeq 6000,SM-OHWY2,CCLF_GB1003-Tumor-SM-OHWY2
SM-OHWY3,CCLF_TWIST65,SM-ONLT8,CO-37520188,E04,SM-OHWY3,DNA:DNA Somatic,62.00,2.02,PT-3DTKJ,NaN,...,PT-3DTKJ,PDO-50107,72.07,Female,RP-3781,[SM-OHWY3],Tumor,Illumina NovaSeq 6000,SM-OHWY3,CCLF_SJ1006-Tumor-SM-OHWY3
SM-OHWY4,CCLF_TWIST65,SM-ONLT9,CO-37520188,E05,SM-OHWY4,DNA:DNA Somatic,62.00,1.61,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,56.05,,RP-3781,[SM-OHWY4],Tumor,Illumina NovaSeq 6000,SM-OHWY4,COLO007-Tumor-SM-OHWY4
SM-OHWY5,CCLF_TWIST65,SM-ONLTO,CO-37520188,H02,SM-OHWY5,DNA:DNA Somatic,62.00,2.15,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,59.30,,RP-3781,[SM-OHWY5],Tumor,Illumina NovaSeq 6000,SM-OHWY5,COLO007-Tumor-SM-OHWY5
SM-OHWY6,CCLF_TWIST65,SM-ONLTE,CO-37520188,F04,SM-OHWY6,DNA:DNA Somatic,62.00,2.01,PT-238DV,NaN,...,PT-238DV,PDO-50107,99.50,,RP-3781,[SM-OHWY6],Tumor,Illumina NovaSeq 6000,SM-OHWY6,AB053-Tumor-SM-OHWY6
SM-OHWY8,CCLF_TWIST65,SM-ONLSL,CO-37520188,A06,SM-OHWY8,DNA:DNA Somatic,62.00,0.62,PT-44IXO,NaN,...,PT-44IXO,PDO-50107,99.62,Male,RP-3781,[SM-OHWY8],Tumor,Illumina NovaSeq 6000,SM-OHWY8,CCLF_SK1182-Tumor-SM-OHWY8
SM-OHWY9,CCLF_TWIST65,SM-ONLSQ,CO-37520188,B05,SM-OHWY9,DNA:DNA Somatic,62.00,1.88,PT-44IXQ,NaN,...,PT-44IXQ,PDO-50107,99.49,Male,RP-3781,[SM-OHWY9],Tumor,Illumina NovaSeq 6000,SM-OHWY9,CCLF_SK1183-Tumor-SM-OHWY9
SM-OHWYA,CCLF_TWIST65,SM-ONLTN,CO-37520188,H01,SM-OHWYA,DNA:DNA Somatic,62.00,2.13,PT-3DTKR,NaN,...,PT-3DTKR,PDO-50107,99.57,Male,RP-3781,[SM-OHWYA],Tumor,Illumina NovaSeq 6000,SM-OHWYA,CCLF_SJ1010-Tumor-SM-OHWYA
SM-OHWYB,CCLF_TWIST65,SM-ONLT4,CO-37520188,D06,SM-OHWYB,DNA:DNA Somatic,62.00,1.82,PT-457I9,NaN,...,PT-457I9,PDO-50107,99.43,,RP-3781,[SM-OHWYB],Tumor,Illumina NovaSeq 6000,SM-OHWYB,CCLF_GB1008-Tumor-SM-OHWYB
SM-OHWYC,CCLF_TWIST65,SM-ONLTR,CO-37520188,H05,SM-OHWYC,DNA:DNA Somatic,62.00,2.43,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,56.23,,RP-3781,[SM-OHWYC],Tumor,Illumina NovaSeq 6000,SM-OHWYC,COLO007-Tumor-SM-OHWYC
SM-OHWYD,CCLF_TWIST65,SM-ONLSP,CO-37520188,B04,SM-OHWYD,DNA:DNA Somatic,62.00,1.70,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,55.99,,RP-3781,[SM-OHWYD],Tumor,Illumina NovaSeq 6000,SM-OHWYD,COLO007-Tumor-SM-OHWYD
SM-OHWYE,CCLF_TWIST65,SM-ONLSR,CO-37520188,B06,SM-OHWYE,DNA:DNA Somatic,62.00,1.79,PT-238AW,NaN,...,PT-238AW,PDO-50107,99.51,,RP-3781,[SM-OHWYE],Tumor,Illumina NovaSeq 6000,SM-OHWYE,CCLF_KL1023-Tumor-SM-OHWYE
SM-OHWYF,CCLF_TWIST65,SM-ONLSW,CO-37520188,C05,SM-OHWYF,DNA:DNA Somatic,62.00,2.31,PT-238AW,NaN,...,PT-238AW,PDO-50107,99.49,,RP-3781,[SM-OHWYF],Tumor,Illumina NovaSeq 6000,SM-OHWYF,CCLF_KL1023-Tumor-SM-OHWYF
SM-OHWYG,CCLF_TWIST65,SM-ONLSI,CO-37520188,A03,SM-OHWYG,DNA:DNA Somatic,62.00,1.92,PT-44IXQ,NaN,...,PT-44IXQ,PDO-50107,99.45,Male,RP-3781,[SM-OHWYG],Tumor,Illumina NovaSeq 6000,SM-OHWYG,CCLF_SK1183-Tumor-SM-OHWYG
SM-OHWYI,CCLF_TWIST65,SM-ONLSG,CO-37520188,A01,SM-OHWYI,DNA:DNA Somatic,62.00,2.12,PT-3P1OX,NaN,...,PT-3P1OX,PDO-50107,99.52,Female,RP-3781,[SM-OHWYI],Tumor,Illumina NovaSeq 6000,SM-OHWYI,CCLF_SJ1049-Tumor-SM-OHWYI
SM-OIKUP,CCLF_TWIST65,SM-ONLSJ,CO-37520188,A04,SM-OIKUP,DNA:DNA Somatic,62.00,1.82,PT-2FK5B,NaN,...,PT-2FK5B,PDO-50107,99.52,Male,RP-3781,[SM-OIKUP],Tumor,Illumina NovaSeq 6000,SM-OIKUP,CCLF_AB1090-Tumor-SM-OIKUP
SM-OIKUQ,CCLF_TWIST65,SM-ONLSX,CO-37520188,C06,SM-OIKUQ,DNA:DNA Somatic,62.00,1.96,PT-3DTKF,NaN,...,PT-3DTKF,PDO-50107,99.52,Female,RP-3781,[SM-OIKUQ],Tumor,Illumina NovaSeq 6000,SM-OIKUQ,CCLF_SJ1004-Tumor-SM-OIKUQ
SM-OIKUR,CCLF_TWIST65,SM-ONLTJ,CO-37520188,G03,SM-OIKUR,DNA:DNA Somatic,62.00,1.86,PT-3CX8D,NaN,...,PT-3CX8D,PDO-50107,99.41,Male,RP-3781,[SM-OIKUR],Tumor,Illumina NovaSeq 6000,SM-OIKUR,CCLF_MDA1135-Tumor-SM-OIKUR
SM-OIKUS,CCLF_TWIST65,SM-ONLTL,CO-37520188,G05,SM-OIKUS,DNA:DNA Somatic,62.00,1.78,PT-1WX5W,NaN,...,PT-1WX5W,PDO-50107,99.52,,RP-3781,[SM-OIKUS],Tumor,Illumina NovaSeq 6000,SM-OIKUS,BT921-Tumor-SM-OIKUS
SM-OIKUT,CCLF_TWIST65,SM-ONLTB,CO-37520188,F01,SM-OIKUT,DNA:DNA Somatic,62.00,1.93,PT-35UDD,NaN,...,PT-35UDD,PDO-50107,99.53,Female,RP-3781,[SM-OIKUT],Tumor,Illumina NovaSeq 6000,SM-OIKUT,CCLF_AB1168-Tumor-SM-OIKUT
SM-OIKUU,CCLF_TWIST65,SM-ONLTG,CO-37520188,F06,SM-OIKUU,DNA:DNA Somatic,62.00,1.78,PT-3DTKP,NaN,...,PT-3DTKP,PDO-50107,56.81,Male,RP-3781,[SM-OIKUU],Tumor,Illumina NovaSeq 6000,SM-OIKUU,CCLF_SJ1009-Tumor-SM-OIKUU
SM-OIKUV,CCLF_TWIST65,SM-ONLT7,CO-37520188,E03,SM-OIKUV,DNA:DNA Somatic,62.00,1.85,PT-3ZINH,NaN,...,PT-3ZINH,PDO-50107,99.55,Female,RP-3781,[SM-OIKUV],Tumor,Illumina NovaSeq 6000,SM-OIKUV,CCLF_GB1004-Tumor-SM-OIKUV
SM-OIKUW,CCLF_TWIST65,SM-ONLSS,CO-37520188,C01,SM-OIKUW,DNA:DNA Somatic,62.00,1.93,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,54.41,Male,RP-3781,[SM-OIKUW],Tumor,Illumina NovaSeq 6000,SM-OIKUW,CCLF_SJ1067-Tumor-SM-OIKUW
SM-OIKUX,CCLF_TWIST65,SM-ONLT5,CO-37520188,E01,SM-OIKUX,DNA:DNA Somatic,62.00,1.69,PT-2NPEJ,NaN,...,PT-2NPEJ,PDO-50107,99.46,Male,RP-3781,[SM-OIKUX],Tumor,Illumina NovaSeq 6000,SM-OIKUX,CCLF_KL1338-Tumor-SM-OIKUX
SM-OIKUY,CCLF_TWIST65,SM-ONLSU,CO-37520188,C03,SM-OIKUY,DNA:DNA Somatic,62.00,1.74,PT-338BW,NaN,...,PT-338BW,PDO-50107,99.47,Male,RP-3781,[SM-OIKUY],Tumor,Illumina NovaSeq 6000,SM-OIKUY,CCLF_MDA1031-Tumor-SM-OIKUY
SM-OIKUZ,CCLF_TWIST65,SM-ONLSO,CO-37520188,B03,SM-OIKUZ,DNA:DNA Somatic,62.00,2.03,PT-3MDJC,NaN,...,PT-3MDJC,PDO-50107,99.52,Female,RP-3781,[SM-OIKUZ],Tumor,Illumina NovaSeq 6000,SM-OIKUZ,CCLF_SJ1037-Tumor-SM-OIKUZ
SM-OIKV1,CCLF_TWIST65,SM-ONLT6,CO-37520188,E02,SM-OIKV1,DNA:DNA Somatic,62.00,1.79,PT-2CJLL,NaN,...,PT-2CJLL,PDO-50107,99.41,Male,RP-3781,[SM-OIKV1],Tumor,Illumina NovaSeq 6000,SM-OIKV1,CCLF_PEDS1104-Tumor-SM-OIKV1
SM-OIKV2,CCLF_TWIST65,SM-ONLSM,CO-37520188,B01,SM-OIKV2,DNA:DNA Somatic,62.00,1.76,PT-3QKBT,NaN,...,PT-3QKBT,PDO-50107,98.85,Male,RP-3781,[SM-OIKV2],Tumor,Illumina NovaSeq 6000,SM-OIKV2,CCLF_SK1176-Tumor-SM-OIKV2
SM-OIKV3,CCLF_TWIST65,SM-ONLTA,CO-37520188,E06,SM-OIKV3,DNA:DNA Somatic,62.00,1.84,PT-3QKBT,NaN,...,PT-3QKBT,PDO-50107,97.65,Male,RP-3781,[SM-OIKV3],Tumor,Illumina NovaSeq 6000,SM-OIKV3,CCLF_SK1176-Tumor-SM-OIKV3
SM-OIKV4,CCLF_TWIST65,SM-ONLTF,CO-37520188,F05,SM-OIKV4,DNA:DNA Somatic,62.00,1.90,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,56.61,Male,RP-3781,[SM-OIKV4],Tumor,Illumina NovaSeq 6000,SM-OIKV4,CCLF_SJ1067-Tumor-SM-OIKV4
SM-OIKV5,CCLF_TWIST65,SM-ONLTM,CO-37520188,G06,SM-OIKV5,DNA:DNA Somatic,62.00,1.95,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,56.00,Male,RP-3781,[SM-OIKV5],Tumor,Illumina NovaSeq 6000,SM-OIKV5,CCLF_SJ1067-Tumor-SM-OIKV5
SM-OIKV6,CCLF_TWIST65,SM-ONLST,CO-37520188,C02,SM-OIKV6,DNA:DNA Somatic,62.00,1.83,PT-3DTKB,NaN,...,PT-3DTKB,PDO-50107,99.50,Female,RP-3781,[SM-OIKV6],Tumor,Illumina NovaSeq 6000,SM-OIKV6,CCLF_SJ1002-Tumor-SM-OIKV6
SM-OIKV7,CCLF_TWIST65,SM-ONLSN,CO-37520188,B02,SM-OIKV7,DNA:DNA Somatic,62.00,1.99,PT-248NV,NaN,...,PT-248NV,PDO-50107,99.43,,RP-3781,[SM-OIKV7],Tumor,Illumina NovaSeq 6000,SM-OIKV7,CCLF_AB1004-Tumor-SM-OIKV7
SM-OIKV8,CCLF_TWIST65,SM-ONLTP,CO-37520188,H03,SM-OIKV8,DNA:DNA Somatic,62.00,1.95,PT-29B72,NaN,...,PT-29B72,PDO-50107,99.46,Male,RP-3781,[SM-OIKV8],Tumor,Illumina NovaSeq 6000,SM-OIKV8,CCLF_AB1052-Tumor-SM-OIKV8
SM-OIKV9,CCLF_TWIST65,SM-ONLTK,CO-37520188,G04,SM-OIKV9,DNA:DNA Somatic,62.00,1.88,PT-3P1OV,NaN,...,PT-3P1OV,PDO-50107,95.70,Male,RP-3781,[SM-OIKV9],Tumor,Illumina NovaSeq 6000,SM-OIKV9,CCLF_SJ1048-Tumor-SM-OIKV9
SM-OIKVA,CCLF_TWIST65,SM-ONLTI,CO-37520188,G02,SM-OIKVA,DNA:DNA Somatic,62.00,1.82,PT-3DTKT,NaN,...,PT-3DTKT,PDO-50107,57.70,Male,RP-3781,[SM-OIKVA],Tumor,Illumina NovaSeq 6000,SM-OIKVA,CCLF_SJ1011-Tumor-SM-OIKVA
SM-OIKVB,CCLF_TWIST65,SM-ONLSV,CO-37520188,C04,SM-OIKVB,DNA:DNA Somatic,62.00,2.01,PT-2CT34,NaN,...,PT-2CT34,PDO-50107,99.41,,RP-3781,[SM-OIKVB],Tumor,Illumina NovaSeq 6000,SM-OIKVB,CCLF_RCRF1053-Tumor-SM-OIKVB

# TODO: check weirdly formatted NAs

In [10]:
# further check weirdly formatted NAs:
for c in tolook:
    assert(df[c].str.startswith("#N/A").any() == False)

In [11]:
# only keep samples that have all the appropriate metadata information
df = check_required_metadata_columns(df, required_metadata_cols=tolook, cohorts2id_url=cohorts2id, drop=True)

No samples are missing any required metadata. Continue running the pipeline.

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:82: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for k, val in df['Collection'].iteritems():

In [12]:
df

,batch,Exported DNA SM-ID,Container,Position,Stock DNA SM-ID,Material Type,Volume,Conc,Participant ID,Parent Sample ID,...,participant_id,pdo,percent_mapped,reported_sex,research_project,root_sample_ids,sample_type,sequencer_model,tdr:sample_id,sample_id
SM-JKMLF,CCLF_TWIST65,SM-ONLT1,CO-37520188,D03,SM-JKMLF,DNA:DNA Genomic,62.00,2.93,PT-248HW,NaN,...,PT-248HW,PDO-50107,99.49,Female,RP-3781,[SM-JKMLF],Normal,Illumina NovaSeq 6000,SM-JKMLF,CCLF_RCRF1003-Normal-SM-JKMLF
SM-JKMLG,CCLF_TWIST65,SM-ONLTC,CO-37520188,F02,SM-JKMLG,DNA:DNA Genomic,62.00,2.43,PT-2H9KW,NaN,...,PT-2H9KW,PDO-50107,99.43,Male,RP-3781,[SM-JKMLG],Normal,Illumina NovaSeq 6000,SM-JKMLG,CCLF_cRCRF1045-Normal-SM-JKMLG
SM-JKMLH,CCLF_TWIST65,SM-ONLTH,CO-37520188,G01,SM-JKMLH,DNA:DNA Genomic,131.44,2.19,PT-2HF4C,NaN,...,PT-2HF4C,PDO-50107,99.47,Female,RP-3781,[SM-JKMLH],Normal,Illumina NovaSeq 6000,SM-JKMLH,CCLF_cRCRF1047-Normal-SM-JKMLH
SM-LYFLX,CCLF_TWIST65,SM-ONLT2,CO-37520188,D04,SM-LYFLX,DNA:DNA Somatic,508.09,2.26,PT-2DWMB,NaN,...,PT-2DWMB,PDO-50107,99.45,,RP-3781,[SM-LYFLX],Normal,Illumina NovaSeq 6000,SM-LYFLX,CCLF_RCRF1060-Normal-SM-LYFLX
SM-M1DNP,CCLF_TWIST65,SM-ONLSZ,CO-37520188,D02,SM-M1DNP,DNA:DNA Somatic,262.88,2.63,PT-28FWN,NaN,...,PT-28FWN,PDO-50107,99.53,Female,RP-3781,[SM-M1DNP],Normal,Illumina NovaSeq 6000,SM-M1DNP,CCLF_RCRF1022-Normal-SM-M1DNP
SM-N1LYI,CCLF_TWIST65,SM-ONLT3,CO-37520188,D05,SM-N1LYI,DNA:DNA Somatic,62.00,2.04,PT-3MGXR,NaN,...,PT-3MGXR,PDO-50107,99.49,Female,RP-3781,[SM-N1LYI],Normal,Illumina NovaSeq 6000,SM-N1LYI,CCLF_RCRF1189-Normal-SM-N1LYI
SM-N1LYJ,CCLF_TWIST65,SM-ONLSY,CO-37520188,D01,SM-N1LYJ,DNA:DNA Somatic,62.00,3.17,PT-3MGXT,NaN,...,PT-3MGXT,PDO-50107,99.56,Female,RP-3781,[SM-N1LYJ],Normal,Illumina NovaSeq 6000,SM-N1LYJ,CCLF_RCRF1190-Normal-SM-N1LYJ
SM-NEJCO,CCLF_TWIST65,SM-ONLTD,CO-37520188,F03,SM-NEJCO,DNA:DNA Somatic,152.52,2.19,PT-3EI5T,NaN,...,PT-3EI5T,PDO-50107,99.48,Male,RP-3781,[SM-NEJCO],Normal,Illumina NovaSeq 6000,SM-NEJCO,CCLF_NB1015-Normal-SM-NEJCO
SM-OHWXY,CCLF_TWIST65,SM-ONLSH,CO-37520188,A02,SM-OHWXY,DNA:DNA Somatic,62.00,1.83,PT-3P1PQ,NaN,...,PT-3P1PQ,PDO-50107,99.44,Male,RP-3781,[SM-OHWXY],Tumor,Illumina NovaSeq 6000,SM-OHWXY,CCLF_SJ1063-Tumor-SM-OHWXY
SM-OHWXZ,CCLF_TWIST65,SM-ONLTQ,CO-37520188,H04,SM-OHWXZ,DNA:DNA Somatic,62.00,2.18,PT-25H83,NaN,...,PT-25H83,PDO-50107,99.49,,RP-3781,[SM-OHWXZ],Tumor,Illumina NovaSeq 6000,SM-OHWXZ,CCLF_KL1081-Tumor-SM-OHWXZ
SM-OHWY2,CCLF_TWIST65,SM-ONLSK,CO-37520188,A05,SM-OHWY2,DNA:DNA Somatic,62.00,1.61,PT-3Y9US,NaN,...,PT-3Y9US,PDO-50107,99.49,Female,RP-3781,[SM-OHWY2],Tumor,Illumina NovaSeq 6000,SM-OHWY2,CCLF_GB1003-Tumor-SM-OHWY2
SM-OHWY3,CCLF_TWIST65,SM-ONLT8,CO-37520188,E04,SM-OHWY3,DNA:DNA Somatic,62.00,2.02,PT-3DTKJ,NaN,...,PT-3DTKJ,PDO-50107,72.07,Female,RP-3781,[SM-OHWY3],Tumor,Illumina NovaSeq 6000,SM-OHWY3,CCLF_SJ1006-Tumor-SM-OHWY3
SM-OHWY4,CCLF_TWIST65,SM-ONLT9,CO-37520188,E05,SM-OHWY4,DNA:DNA Somatic,62.00,1.61,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,56.05,,RP-3781,[SM-OHWY4],Tumor,Illumina NovaSeq 6000,SM-OHWY4,COLO007-Tumor-SM-OHWY4
SM-OHWY5,CCLF_TWIST65,SM-ONLTO,CO-37520188,H02,SM-OHWY5,DNA:DNA Somatic,62.00,2.15,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,59.30,,RP-3781,[SM-OHWY5],Tumor,Illumina NovaSeq 6000,SM-OHWY5,COLO007-Tumor-SM-OHWY5
SM-OHWY6,CCLF_TWIST65,SM-ONLTE,CO-37520188,F04,SM-OHWY6,DNA:DNA Somatic,62.00,2.01,PT-238DV,NaN,...,PT-238DV,PDO-50107,99.50,,RP-3781,[SM-OHWY6],Tumor,Illumina NovaSeq 6000,SM-OHWY6,AB053-Tumor-SM-OHWY6
SM-OHWY8,CCLF_TWIST65,SM-ONLSL,CO-37520188,A06,SM-OHWY8,DNA:DNA Somatic,62.00,0.62,PT-44IXO,NaN,...,PT-44IXO,PDO-50107,99.62,Male,RP-3781,[SM-OHWY8],Tumor,Illumina NovaSeq 6000,SM-OHWY8,CCLF_SK1182-Tumor-SM-OHWY8
SM-OHWY9,CCLF_TWIST65,SM-ONLSQ,CO-37520188,B05,SM-OHWY9,DNA:DNA Somatic,62.00,1.88,PT-44IXQ,NaN,...,PT-44IXQ,PDO-50107,99.49,Male,RP-3781,[SM-OHWY9],Tumor,Illumina NovaSeq 6000,SM-OHWY9,CCLF_SK1183-Tumor-SM-OHWY9
SM-OHWYA,CCLF_TWIST65,SM-ONLTN,CO-37520188,H01,SM-OHWYA,DNA:DNA Somatic,62.00,2.13,PT-3DTKR,NaN,...,PT-3DTKR,PDO-50107,99.57,Male,RP-3781,[SM-OHWYA],Tumor,Illumina NovaSeq 6000,SM-OHWYA,CCLF_SJ1010-Tumor-SM-OHWYA
SM-OHWYB,CCLF_TWIST65,SM-ONLT4,CO-37520188,D06,SM-OHWYB,DNA:DNA Somatic,62.00,1.82,PT-457I9,NaN,...,PT-457I9,PDO-50107,99.43,,RP-3781,[SM-OHWYB],Tumor,Illumina NovaSeq 6000,SM-OHWYB,CCLF_GB1008-Tumor-SM-OHWYB
SM-OHWYC,CCLF_TWIST65,SM-ONLTR,CO-37520188,H05,SM-OHWYC,DNA:DNA Somatic,62.00,2.43,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,56.23,,RP-3781,[SM-OHWYC],Tumor,Illumina NovaSeq 6000,SM-OHWYC,COLO007-Tumor-SM-OHWYC
SM-OHWYD,CCLF_TWIST65,SM-ONLSP,CO-37520188,B04,SM-OHWYD,DNA:DNA Somatic,62.00,1.70,PT-1I4WO,NaN,...,PT-1I4WO,PDO-50107,55.99,,RP-3781,[SM-OHWYD],Tumor,Illumina NovaSeq 6000,SM-OHWYD,COLO007-Tumor-SM-OHWYD
SM-OHWYE,CCLF_TWIST65,SM-ONLSR,CO-37520188,B06,SM-OHWYE,DNA:DNA Somatic,62.00,1.79,PT-238AW,NaN,...,PT-238AW,PDO-50107,99.51,,RP-3781,[SM-OHWYE],Tumor,Illumina NovaSeq 6000,SM-OHWYE,CCLF_KL1023-Tumor-SM-OHWYE
SM-OHWYF,CCLF_TWIST65,SM-ONLSW,CO-37520188,C05,SM-OHWYF,DNA:DNA Somatic,62.00,2.31,PT-238AW,NaN,...,PT-238AW,PDO-50107,99.49,,RP-3781,[SM-OHWYF],Tumor,Illumina NovaSeq 6000,SM-OHWYF,CCLF_KL1023-Tumor-SM-OHWYF
SM-OHWYG,CCLF_TWIST65,SM-ONLSI,CO-37520188,A03,SM-OHWYG,DNA:DNA Somatic,62.00,1.92,PT-44IXQ,NaN,...,PT-44IXQ,PDO-50107,99.45,Male,RP-3781,[SM-OHWYG],Tumor,Illumina NovaSeq 6000,SM-OHWYG,CCLF_SK1183-Tumor-SM-OHWYG
SM-OHWYI,CCLF_TWIST65,SM-ONLSG,CO-37520188,A01,SM-OHWYI,DNA:DNA Somatic,62.00,2.12,PT-3P1OX,NaN,...,PT-3P1OX,PDO-50107,99.52,Female,RP-3781,[SM-OHWYI],Tumor,Illumina NovaSeq 6000,SM-OHWYI,CCLF_SJ1049-Tumor-SM-OHWYI
SM-OIKUP,CCLF_TWIST65,SM-ONLSJ,CO-37520188,A04,SM-OIKUP,DNA:DNA Somatic,62.00,1.82,PT-2FK5B,NaN,...,PT-2FK5B,PDO-50107,99.52,Male,RP-3781,[SM-OIKUP],Tumor,Illumina NovaSeq 6000,SM-OIKUP,CCLF_AB1090-Tumor-SM-OIKUP
SM-OIKUQ,CCLF_TWIST65,SM-ONLSX,CO-37520188,C06,SM-OIKUQ,DNA:DNA Somatic,62.00,1.96,PT-3DTKF,NaN,...,PT-3DTKF,PDO-50107,99.52,Female,RP-3781,[SM-OIKUQ],Tumor,Illumina NovaSeq 6000,SM-OIKUQ,CCLF_SJ1004-Tumor-SM-OIKUQ
SM-OIKUR,CCLF_TWIST65,SM-ONLTJ,CO-37520188,G03,SM-OIKUR,DNA:DNA Somatic,62.00,1.86,PT-3CX8D,NaN,...,PT-3CX8D,PDO-50107,99.41,Male,RP-3781,[SM-OIKUR],Tumor,Illumina NovaSeq 6000,SM-OIKUR,CCLF_MDA1135-Tumor-SM-OIKUR
SM-OIKUS,CCLF_TWIST65,SM-ONLTL,CO-37520188,G05,SM-OIKUS,DNA:DNA Somatic,62.00,1.78,PT-1WX5W,NaN,...,PT-1WX5W,PDO-50107,99.52,,RP-3781,[SM-OIKUS],Tumor,Illumina NovaSeq 6000,SM-OIKUS,BT921-Tumor-SM-OIKUS
SM-OIKUT,CCLF_TWIST65,SM-ONLTB,CO-37520188,F01,SM-OIKUT,DNA:DNA Somatic,62.00,1.93,PT-35UDD,NaN,...,PT-35UDD,PDO-50107,99.53,Female,RP-3781,[SM-OIKUT],Tumor,Illumina NovaSeq 6000,SM-OIKUT,CCLF_AB1168-Tumor-SM-OIKUT
SM-OIKUU,CCLF_TWIST65,SM-ONLTG,CO-37520188,F06,SM-OIKUU,DNA:DNA Somatic,62.00,1.78,PT-3DTKP,NaN,...,PT-3DTKP,PDO-50107,56.81,Male,RP-3781,[SM-OIKUU],Tumor,Illumina NovaSeq 6000,SM-OIKUU,CCLF_SJ1009-Tumor-SM-OIKUU
SM-OIKUV,CCLF_TWIST65,SM-ONLT7,CO-37520188,E03,SM-OIKUV,DNA:DNA Somatic,62.00,1.85,PT-3ZINH,NaN,...,PT-3ZINH,PDO-50107,99.55,Female,RP-3781,[SM-OIKUV],Tumor,Illumina NovaSeq 6000,SM-OIKUV,CCLF_GB1004-Tumor-SM-OIKUV
SM-OIKUW,CCLF_TWIST65,SM-ONLSS,CO-37520188,C01,SM-OIKUW,DNA:DNA Somatic,62.00,1.93,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,54.41,Male,RP-3781,[SM-OIKUW],Tumor,Illumina NovaSeq 6000,SM-OIKUW,CCLF_SJ1067-Tumor-SM-OIKUW
SM-OIKUX,CCLF_TWIST65,SM-ONLT5,CO-37520188,E01,SM-OIKUX,DNA:DNA Somatic,62.00,1.69,PT-2NPEJ,NaN,...,PT-2NPEJ,PDO-50107,99.46,Male,RP-3781,[SM-OIKUX],Tumor,Illumina NovaSeq 6000,SM-OIKUX,CCLF_KL1338-Tumor-SM-OIKUX
SM-OIKUY,CCLF_TWIST65,SM-ONLSU,CO-37520188,C03,SM-OIKUY,DNA:DNA Somatic,62.00,1.74,PT-338BW,NaN,...,PT-338BW,PDO-50107,99.47,Male,RP-3781,[SM-OIKUY],Tumor,Illumina NovaSeq 6000,SM-OIKUY,CCLF_MDA1031-Tumor-SM-OIKUY
SM-OIKUZ,CCLF_TWIST65,SM-ONLSO,CO-37520188,B03,SM-OIKUZ,DNA:DNA Somatic,62.00,2.03,PT-3MDJC,NaN,...,PT-3MDJC,PDO-50107,99.52,Female,RP-3781,[SM-OIKUZ],Tumor,Illumina NovaSeq 6000,SM-OIKUZ,CCLF_SJ1037-Tumor-SM-OIKUZ
SM-OIKV1,CCLF_TWIST65,SM-ONLT6,CO-37520188,E02,SM-OIKV1,DNA:DNA Somatic,62.00,1.79,PT-2CJLL,NaN,...,PT-2CJLL,PDO-50107,99.41,Male,RP-3781,[SM-OIKV1],Tumor,Illumina NovaSeq 6000,SM-OIKV1,CCLF_PEDS1104-Tumor-SM-OIKV1
SM-OIKV2,CCLF_TWIST65,SM-ONLSM,CO-37520188,B01,SM-OIKV2,DNA:DNA Somatic,62.00,1.76,PT-3QKBT,NaN,...,PT-3QKBT,PDO-50107,98.85,Male,RP-3781,[SM-OIKV2],Tumor,Illumina NovaSeq 6000,SM-OIKV2,CCLF_SK1176-Tumor-SM-OIKV2
SM-OIKV3,CCLF_TWIST65,SM-ONLTA,CO-37520188,E06,SM-OIKV3,DNA:DNA Somatic,62.00,1.84,PT-3QKBT,NaN,...,PT-3QKBT,PDO-50107,97.65,Male,RP-3781,[SM-OIKV3],Tumor,Illumina NovaSeq 6000,SM-OIKV3,CCLF_SK1176-Tumor-SM-OIKV3
SM-OIKV4,CCLF_TWIST65,SM-ONLTF,CO-37520188,F05,SM-OIKV4,DNA:DNA Somatic,62.00,1.90,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,56.61,Male,RP-3781,[SM-OIKV4],Tumor,Illumina NovaSeq 6000,SM-OIKV4,CCLF_SJ1067-Tumor-SM-OIKV4
SM-OIKV5,CCLF_TWIST65,SM-ONLTM,CO-37520188,G06,SM-OIKV5,DNA:DNA Somatic,62.00,1.95,PT-3P1PY,NaN,...,PT-3P1PY,PDO-50107,56.00,Male,RP-3781,[SM-OIKV5],Tumor,Illumina NovaSeq 6000,SM-OIKV5,CCLF_SJ1067-Tumor-SM-OIKV5
SM-OIKV6,CCLF_TWIST65,SM-ONLST,CO-37520188,C02,SM-OIKV6,DNA:DNA Somatic,62.00,1.83,PT-3DTKB,NaN,...,PT-3DTKB,PDO-50107,99.50,Female,RP-3781,[SM-OIKV6],Tumor,Illumina NovaSeq 6000,SM-OIKV6,CCLF_SJ1002-Tumor-SM-OIKV6
SM-OIKV7,CCLF_TWIST65,SM-ONLSN,CO-37520188,B02,SM-OIKV7,DNA:DNA Somatic,62.00,1.99,PT-248NV,NaN,...,PT-248NV,PDO-50107,99.43,,RP-3781,[SM-OIKV7],Tumor,Illumina NovaSeq 6000,SM-OIKV7,CCLF_AB1004-Tumor-SM-OIKV7
SM-OIKV8,CCLF_TWIST65,SM-ONLTP,CO-37520188,H03,SM-OIKV8,DNA:DNA Somatic,62.00,1.95,PT-29B72,NaN,...,PT-29B72,PDO-50107,99.46,Male,RP-3781,[SM-OIKV8],Tumor,Illumina NovaSeq 6000,SM-OIKV8,CCLF_AB1052-Tumor-SM-OIKV8
SM-OIKV9,CCLF_TWIST65,SM-ONLTK,CO-37520188,G04,SM-OIKV9,DNA:DNA Somatic,62.00,1.88,PT-3P1OV,NaN,...,PT-3P1OV,PDO-50107,95.70,Male,RP-3781,[SM-OIKV9],Tumor,Illumina NovaSeq 6000,SM-OIKV9,CCLF_SJ1048-Tumor-SM-OIKV9
SM-OIKVA,CCLF_TWIST65,SM-ONLTI,CO-37520188,G02,SM-OIKVA,DNA:DNA Somatic,62.00,1.82,PT-3DTKT,NaN,...,PT-3DTKT,PDO-50107,57.70,Male,RP-3781,[SM-OIKVA],Tumor,Illumina NovaSeq 6000,SM-OIKVA,CCLF_SJ1011-Tumor-SM-OIKVA
SM-OIKVB,CCLF_TWIST65,SM-ONLSV,CO-37520188,C04,SM-OIKVB,DNA:DNA Somatic,62.00,2.01,PT-2CT34,NaN,...,PT-2CT34,PDO-50107,99.41,,RP-3781,[SM-OIKVB],Tumor,Illumina NovaSeq 6000,SM-OIKVB,CCLF_RCRF1053-Tumor-SM-OIKVB

In [13]:
# generate sample df to upload to Terra
sample_info = create_sample_df_for_terra(wto, df, cohorts2id_url=cohorts2id)

# sanity check: this should be what you plan on uploading to Terra
print(sample_info.shape)
display(sample_info.head())

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:82: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for k, val in df['Collection'].iteritems():

creating new sample information df
(47, 23)

,crai_or_bai_path,cram_or_bam_path,batch,individual_id,reference_id,patient_id,participant,aggregation_product_name_validation,external_id_validation,bsp_sample_id_validation,...,tumor_subtype,squid_sample_id_validation,source_subtype_validation,processed_subtype_validation,primary_disease,media,Collection,cohorts,tissue_site,source
sample_id,,,,,,,,,,,,,,,,,,,,,
SM-JKMLF,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1003,SM-JKMLF,PT-248HW,CCLF_RCRF1003,BroadPanCancer2019,CCLF_RCRF1003N_GL_50,SM-JKMLF,...,NaN,CCLF_RCRF1003N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,fibrolamellar hepatocellular carcinoma,NaN,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLG,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1045,SM-JKMLG,PT-2H9KW,CCLF_cRCRF1045,BroadPanCancer2019,CCLF_cRCRF1045N_GL_50,SM-JKMLG,...,NaN,CCLF_cRCRF1045N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,Non-small cell lung cancer,NaN,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLH,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1047,SM-JKMLH,PT-2HF4C,CCLF_cRCRF1047,BroadPanCancer2019,CCLF_cRCRF1066N_GL_50,SM-JKMLH,...,NaN,CCLF_cRCRF1066N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,stomach adenocarcinoma,NaN,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-LYFLX,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1060,SM-LYFLX,PT-2DWMB,CCLF_RCRF1060,BroadPanCancer2019,CCLF_RCRF1060N_GL_18,SM-LYFLX,...,NaN,CCLF_RCRF1060N_GL_18,Tissue:Fresh Tissue,DNA:DNA Somatic,Angiosarcoma,NaN,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Abdominal Cavity,CCLF
SM-M1DNP,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1022,SM-M1DNP,PT-28FWN,CCLF_RCRF1022,BroadPanCancer2019,CCLF_RCRF1180N_GL_14,SM-M1DNP,...,NaN,CCLF_RCRF1180N_GL_14,Tissue:Fresh Tissue,DNA:DNA Somatic,Leiomyosarcoma,NaN,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Stomach,CCLF

In [14]:
# Run this chunk to save the sample_info TSV to a file. I highly recommend this when running a pipeline on a new batch.
# This way, if anything goes wrong in the workspace, you can fall back to this.

## check: create directory "data/sample_infos" if does not exist
filepath = 'data/sample_infos/%s_sample_info.tsv' % '_'.join(samplesetnames)
sample_info.to_csv(filepath, sep='\t')

In [32]:
# read in the file you just saved
filepath = 'data/sample_infos/%s_sample_info.tsv' % '_'.join(samplesetnames)
sample_info = pd.read_csv(filepath, sep = '\t', na_filter = False)
sample_info = sample_info.set_index('sample_id')
print(sample_info.shape)
sample_info.head()

(47, 23)

,crai_or_bai_path,cram_or_bam_path,batch,individual_id,reference_id,patient_id,participant,aggregation_product_name_validation,external_id_validation,bsp_sample_id_validation,...,tumor_subtype,squid_sample_id_validation,source_subtype_validation,processed_subtype_validation,primary_disease,media,Collection,cohorts,tissue_site,source
sample_id,,,,,,,,,,,,,,,,,,,,,
SM-JKMLF,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1003,SM-JKMLF,PT-248HW,CCLF_RCRF1003,BroadPanCancer2019,CCLF_RCRF1003N_GL_50,SM-JKMLF,...,,CCLF_RCRF1003N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,fibrolamellar hepatocellular carcinoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLG,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1045,SM-JKMLG,PT-2H9KW,CCLF_cRCRF1045,BroadPanCancer2019,CCLF_cRCRF1045N_GL_50,SM-JKMLG,...,,CCLF_cRCRF1045N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,Non-small cell lung cancer,,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLH,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1047,SM-JKMLH,PT-2HF4C,CCLF_cRCRF1047,BroadPanCancer2019,CCLF_cRCRF1066N_GL_50,SM-JKMLH,...,,CCLF_cRCRF1066N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,stomach adenocarcinoma,,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-LYFLX,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1060,SM-LYFLX,PT-2DWMB,CCLF_RCRF1060,BroadPanCancer2019,CCLF_RCRF1060N_GL_18,SM-LYFLX,...,,CCLF_RCRF1060N_GL_18,Tissue:Fresh Tissue,DNA:DNA Somatic,Angiosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Abdominal Cavity,CCLF
SM-M1DNP,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1022,SM-M1DNP,PT-28FWN,CCLF_RCRF1022,BroadPanCancer2019,CCLF_RCRF1180N_GL_14,SM-M1DNP,...,,CCLF_RCRF1180N_GL_14,Tissue:Fresh Tissue,DNA:DNA Somatic,Leiomyosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Stomach,CCLF

# Check if there are duplicate external ids

In [34]:
existing_samples = wto.get_samples()

In [35]:
existing_ids = existing_samples.external_id_validation.tolist()# + sample_info.external_id_validation.tolist()
dups = set([x for x in existing_ids if existing_ids.count(x) > 1])
if len(dups) > 0:
    raise Exception("Found duplicate external validation ids: ", dups, " , check with ops to verify if these need to be renamed.")

In [36]:
sample_info

,crai_or_bai_path,cram_or_bam_path,batch,individual_id,reference_id,patient_id,participant,aggregation_product_name_validation,external_id_validation,bsp_sample_id_validation,...,tumor_subtype,squid_sample_id_validation,source_subtype_validation,processed_subtype_validation,primary_disease,media,Collection,cohorts,tissue_site,source
sample_id,,,,,,,,,,,,,,,,,,,,,
SM-JKMLF,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1003,SM-JKMLF,PT-248HW,CCLF_RCRF1003,BroadPanCancer2019,CCLF_RCRF1003N_GL_50,SM-JKMLF,...,,CCLF_RCRF1003N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,fibrolamellar hepatocellular carcinoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLG,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1045,SM-JKMLG,PT-2H9KW,CCLF_cRCRF1045,BroadPanCancer2019,CCLF_cRCRF1045N_GL_50,SM-JKMLG,...,,CCLF_cRCRF1045N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,Non-small cell lung cancer,,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-JKMLH,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_cRCRF1047,SM-JKMLH,PT-2HF4C,CCLF_cRCRF1047,BroadPanCancer2019,CCLF_cRCRF1066N_GL_50,SM-JKMLH,...,,CCLF_cRCRF1066N_GL_50,Whole Blood:Whole Blood,DNA:DNA Genomic,stomach adenocarcinoma,,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Blood Vessel,CCLF
SM-LYFLX,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1060,SM-LYFLX,PT-2DWMB,CCLF_RCRF1060,BroadPanCancer2019,CCLF_RCRF1060N_GL_18,SM-LYFLX,...,,CCLF_RCRF1060N_GL_18,Tissue:Fresh Tissue,DNA:DNA Somatic,Angiosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Abdominal Cavity,CCLF
SM-M1DNP,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1022,SM-M1DNP,PT-28FWN,CCLF_RCRF1022,BroadPanCancer2019,CCLF_RCRF1180N_GL_14,SM-M1DNP,...,,CCLF_RCRF1180N_GL_14,Tissue:Fresh Tissue,DNA:DNA Somatic,Leiomyosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Stomach,CCLF
SM-N1LYI,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1189,SM-N1LYI,PT-3MGXR,CCLF_RCRF1189,BroadPanCancer2019,CCLF_RCRF1189N_GL_12,SM-N1LYI,...,,CCLF_RCRF1189N_GL_12,Tissue:Fresh Tissue,DNA:DNA Somatic,Angiosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Breast,CCLF
SM-N1LYJ,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1190,SM-N1LYJ,PT-3MGXT,CCLF_RCRF1190,BroadPanCancer2019,CCLF_RCRF1190N_GL_12,SM-N1LYJ,...,,CCLF_RCRF1190N_GL_12,Tissue:Fresh Tissue,DNA:DNA Somatic,Angiosarcoma,,Cancer Cell Line Factory (CCLF) / Brian McStee...,COHORT_CCLF_RCRF,Adrenal Gland,CCLF
SM-NEJCO,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_NB1015,SM-NEJCO,PT-3EI5T,CCLF_NB1015,BroadPanCancer2019,CCLF_NB1015N_GL_4,SM-NEJCO,...,,CCLF_NB1015N_GL_4,Tissue:Fresh Tissue,DNA:DNA Somatic,Fibrolamellar Hepatocellular Carcinoma,,Cancer Cell Line Factory (CCLF) / Nabeel Barde...,COHORT_NB,Liver,CCLF
SM-OHWXY,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1063,SM-OHWXY,PT-3P1PQ,CCLF_SJ1063,BroadPanCancer2019,CCLF_SJ1063T_2_FM_MSCM_P14_2D_1,SM-OHWXY,...,Primary,CCLF_SJ1063T_2_FM_MSCM_P14_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Wilms Tumor,FM/MSCM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Kidney,CCLF
SM-OHWXZ,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_KL1081,SM-OHWXZ,PT-25H83,CCLF_KL1081,BroadPanCancer2019,CCLF_KL1089T_NSA_P18_2D_1,SM-OHWXZ,...,Recurrent,CCLF_KL1089T_NSA_P18_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Glioblastoma multiforme,NSA,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,COHORT_BT,Brain,CCLF
SM-OHWY2,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_GB1003,SM-OHWY2,PT-3Y9US,CCLF_GB1003,BroadPanCancer2019,CCLF_GB1003T_RETM_P6_2D_1,SM-OHWY2,...,Metastatic,CCLF_GB1003T_RETM_P6_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Uveal Melanoma [UVM],RETM,Cancer Cell Line Factory (CCLF) / Genevieve Bo...,COHORT_GB,Peritoneum,CCLF
SM-OHWY3,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1006,SM-OHWY3,PT-3DTKJ,CCLF_SJ1006,BroadPanCancer2019,CCLF_SJ1006T_1_M87_SMGM_P8_2D_1,SM-OHWY3,...,Primary,CCLF_SJ1006T_1_M87_SMGM_P8_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Sclerosing Rhabdomyosarcoma,M87/SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Oropharynx,CCLF
SM-OHWY4,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,COLO007,SM-OHWY4,PT-1I4WO,COLO007,BroadPanCancer2019,COL007T_OPAC_P11_2D_1_1,SM-OHWY4,...,Primary,COL007T_OPAC_P11_2D_1_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Colorectal Cancer,OPAC,Cancer Cell Line Factory (CCLF) / Brian Wolpin...,COHORT_COLO,Colon,CCLF
SM-OHWY5,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,COLO007,SM-OHWY5,PT-1I4WO,COLO007,BroadPanCancer2019,COL007T_OPAC_P11_2D_2_1,SM-OHWY5,...,Primary,COL007T_OPAC_P11_2D_2_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Colorectal Cancer,OPAC,Cancer Cell Line Factory (CCLF) / Brian Wolpin...,COHORT_COLO,Colon,CCLF
SM-OHWY6,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,AB053,SM-OHWY6,PT-238DV,AB053,BroadPanCancer2019,AB053T_SMGM_P17_2D_1,SM-OHWY6,...,,AB053T_SMGM_P17_2D_1,Cells:Growing,DNA:DNA Somatic,Gastric Adenocarcinoma,SMGM,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,COHORT_AB,Stomach,CCLF
SM-OHWY8,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SK1182,SM-OHWY8,PT-44IXO,CCLF_SK1182,BroadPanCancer2019,CCLF_SK1182T_Primary_1,SM-OHWY8,...,Metastatic,CCLF_SK1182T_Primary_1,Tissue:Fresh Tissue,DNA:DNA Somatic,gastroesophageal adenocarcinoma,,Cancer Cell Line Factory (CCLF) / Samuel Klemp...,COHORT_SK,Lymph Node,CCLF
SM-OHWY9,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SK1183,SM-OHWY9,PT-44IXQ,CCLF_SK1183,BroadPanCancer2019,CCLF_SK1183T_Primary_1,SM-OHWY9,...,Metastatic,CCLF_SK1183T_Primary_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Esophageal Carcinoma [ESCA],,Cancer Cell Line Factory (CCLF) / Samuel Klemp...,COHORT_SK,Thoracic Cavity,CCLF
SM-OHWYA,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1010,SM-OHWYA,PT-3DTKR,CCLF_SJ1010,BroadPanCancer2019,CCLF_SJ1010T_1_OPAC_SMGM_P8_2D_1,SM-OHWYA,...,Primary,CCLF_SJ1010T_1_OPAC_SMGM_P8_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Alveolar Rhabdomyosarcoma,OPAC/SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Stomach,CCLF
SM-OHWYB,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_GB1008,SM-OHWYB,PT-457I9,CCLF_GB1008,BroadPanCancer2019,CCLF_GB1008T_Primary_1,SM-OHWYB,...,,CCLF_GB1008T_Primary_1,Bodily Fluid:Ascites,DNA:DNA Somatic,Uveal Melanoma [UVM],,Cancer Cell Line Factory (CCLF) / Genevieve Bo...,COHORT_GB,Abdominal Cavity,CCLF
SM-OHWYC,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,COLO007,SM-OHWYC,PT-1I4WO,COLO007,BroadPanCancer2019,COL007T_FM_RPMI_P16_2D_1,SM-OHWYC,...,Primary,COL007T_FM_RPMI_P16_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Colorectal Cancer,FM/RPMI,Cancer Cell Line Factory (CCLF) / Brian Wolpin...,COHORT_COLO,Colon,CCLF
SM-OHWYD,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,COLO007,SM-OHWYD,PT-1I4WO,COLO007,BroadPanCancer2019,COL007T_OPAC_P16_2D_1,SM-OHWYD,...,Primary,COL007T_OPAC_P16_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Colorectal Cancer,OPAC,Cancer Cell Line Factory (CCLF) / Brian Wolpin...,COHORT_COLO,Colon,CCLF
SM-OHWYE,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_KL1023,SM-OHWYE,PT-238AW,CCLF_KL1023,BroadPanCancer2019,CCLF_KL1023T_NSA_P11_2D_1_1,SM-OHWYE,...,Primary,CCLF_KL1023T_NSA_P11_2D_1_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Glioblastoma multiforme [GBM],NSA,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,COHORT_BT,Brain,CCLF
SM-OHWYF,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_KL1023,SM-OHWYF,PT-238AW,CCLF_KL1023,BroadPanCancer2019,CCLF_KL1023T_NSA_P11_2D_2_1,SM-OHWYF,...,Primary,CCLF_KL1023T_NSA_P11_2D_2_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Glioblastoma multiforme [GBM],NSA,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,COHORT_BT,Brain,CCLF
SM-OHWYG,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SK1183,SM-OHWYG,PT-44IXQ,CCLF_SK1183,BroadPanCancer2019,CCLF_SK1183T_OPAC_P5_3D_1,SM-OHWYG,...,Metastatic,CCLF_SK1183T_OPAC_P5_3D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Esophageal Carcinoma [ESCA],OPAC,Cancer Cell Line Factory (CCLF) / Samuel Klemp...,COHORT_SK,Thoracic Cavity,CCLF
SM-OHWYI,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1049,SM-OHWYI,PT-3P1OX,CCLF_SJ1049,BroadPanCancer2019,CCLF_SJ1049T_1_FM_OPAC_P10_2D_1,SM-OHWYI,...,Metastatic,CCLF_SJ1049T_1_FM_OPAC_P10_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Neuroblastoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Lung,CCLF
SM-OIKUP,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_AB1090,SM-OIKUP,PT-2FK5B,CCLF_AB1090,BroadPanCancer2019,CCLF_AB1090T_FM_P13_2D_1,SM-OIKUP,...,Primary,CCLF_AB1090T_FM_P13_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Esophogeal carcinoma,FM,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,COHORT_AB,Esophagus,CCLF
SM-OIKUQ,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1004,SM-OIKUQ,PT-3DTKF,CCLF_SJ1004,BroadPanCancer2019,CCLF_SJ1004T_2_M87_OGM_P11_2D_1,SM-OIKUQ,...,Primary,CCLF_SJ1004T_2_M87_OGM_P11_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Embryonal Rhabdomyosarcoma,M87/OGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Stomach,CCLF
SM-OIKUR,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_MDA1135,SM-OIKUR,PT-3CX8D,CCLF_MDA1135,BroadPanCancer2019,CCLF_MDA1135T_EGM_OPAC_P13_2D_1,SM-OIKUR,...,Metastatic,CCLF_MDA1135T_EGM_OPAC_P13_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Mucosal Melanoma,EGM/OPAC,Cancer Cell Line Factory (CCLF) / Tim Hefferna...,COHORT_MDA,Neck,CCLF
SM-OIKUS,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,BT921,SM-OIKUS,PT-1WX5W,BT921,BroadPanCancer2019,BT921_NSA_P26_2D_1,SM-OIKUS,...,Primary,BT921_NSA_P26_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,GBM,NSA,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,COHORT_BT,Brain,CCLF
SM-OIKUT,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_AB1168,SM-OIKUT,PT-35UDD,CCLF_AB1168,BroadPanCancer2019,CCLF_AB1168T_FM_P19_2D_1,SM-OIKUT,...,Metastatic,CCLF_AB1168T_FM_P19_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Stomach Adenocarcinoma,FM,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,COHORT_AB,Peritoneal Cavity,CCLF
SM-OIKUU,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1009,SM-OIKUU,PT-3DTKP,CCLF_SJ1009,BroadPanCancer2019,CCLF_SJ1009T_2_MSCM_SMGM_P24_2D_1,SM-OIKUU,...,Metastatic,CCLF_SJ1009T_2_MSCM_SMGM_P24_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Embryonal Rhabdomyosarcoma,MSCM/SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Lung,CCLF
SM-OIKUV,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_GB1004,SM-OIKUV,PT-3ZINH,CCLF_GB1004,BroadPanCancer2019,CCLF_GB1004T_Primary_1,SM-OIKUV,...,Metastatic,CCLF_GB1004T_Primary_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Uveal Melanoma [UVM],,Cancer Cell Line Factory (CCLF) / Genevieve Bo...,COHORT_GB,Soft tissue,CCLF
SM-OIKUW,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1067,SM-OIKUW,PT-3P1PY,CCLF_SJ1067,BroadPanCancer2019,CCLF_SJ1067T_1_FM_OPAC_P11_2D_1,SM-OIKUW,...,Primary,CCLF_SJ1067T_1_FM_OPAC_P11_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Retinoblastoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Eye,CCLF
SM-OIKUX,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_KL1338,SM-OIKUX,PT-2NPEJ,CCLF_KL1338,BroadPanCancer2019,CCLF_KL1338T_EGM_OPAC_P17_2D_1,SM-OIKUX,...,Primary,CCLF_KL1338T_EGM_OPAC_P17_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,medulloblastoma,EGM/OPAC,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,COHORT_BT,Brain,CCLF
SM-OIKUY,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_MDA1031,SM-OIKUY,PT-338BW,CCLF_MDA1031,BroadPanCancer2019,CCLF_MDA1031T_AR5_AR5_Rspo_FBS_P23_2D_1,SM-OIKUY,...,Metastatic,CCLF_MDA1031T_AR5_AR5_Rspo_FBS_P23_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Neuroendocrine Tumor,AR5/Rspo/FBS,Cancer Cell Line Factory (CCLF) / Tim Hefferna...,COHORT_MDA,Liver,CCLF
SM-OIKUZ,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1037,SM-OIKUZ,PT-3MDJC,CCLF_SJ1037,BroadPanCancer2019,CCLF_SJ1037T_2_SMGM_P7_2D_1,SM-OIKUZ,...,Metastatic,CCLF_SJ1037T_2_SMGM_P7_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Ewing Sarcoma,SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Thoracic Cavity,CCLF
SM-OIKV1,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_PEDS1104,SM-OIKV1,PT-2CJLL,CCLF_PEDS1104,BroadPanCancer2019,CCLF_PEDS1113T_CM_P26_2D_1,SM-OIKV1,...,Primary,CCLF_PEDS1113T_CM_P26_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Wilms Tumor,CM,Cancer Cell Line Factory (CCLF) / Hong/Crompto...,COHORT_PEDS,Kidney,CCLF
SM-OIKV2,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SK1176,SM-OIKV2,PT-3QKBT,CCLF_SK1176,BroadPanCancer2019,CCLF_SK1176T_FM_OPAC_P10_2D_1,SM-OIKV2,...,Recurrent,CCLF_SK1176T_FM_OPAC_P10_2D_1,Whole Blood:Whole Blood,DNA:DNA Somatic,Gastroesophageal junction adenocarcinoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Samuel Klemp...,COHORT_SK,Peritoneal Cavity,CCLF
SM-OIKV3,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SK1176,SM-OIKV3,PT-3QKBT,CCLF_SK1176,BroadPanCancer2019,CCLF_SK1176T_RETM_SMGM_P10_2D_1,SM-OIKV3,...,Recurrent,CCLF_SK1176T_RETM_SMGM_P10_2D_1,Whole Blood:Whole Blood,DNA:DNA Somatic,Gastroesophageal junction adenocarcinoma,RETM/SMGM,Cancer Cell Line Factory (CCLF) / Samuel Klemp...,COHORT_SK,Peritoneal Cavity,CCLF
SM-OIKV4,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1067,SM-OIKV4,PT-3P1PY,CCLF_SJ1067,BroadPanCancer2019,CCLF_SJ1067T_1_FM_RPMI_P19_2D_1,SM-OIKV4,...,Primary,CCLF_SJ1067T_1_FM_RPMI_P19_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Retinoblastoma,FM/RPMI,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Eye,CCLF
SM-OIKV5,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1067,SM-OIKV5,PT-3P1PY,CCLF_SJ1067,BroadPanCancer2019,CCLF_SJ1067T_1_FM_OPAC_P18_2D_1,SM-OIKV5,...,Primary,CCLF_SJ1067T_1_FM_OPAC_P18_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Retinoblastoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Eye,CCLF
SM-OIKV6,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1002,SM-OIKV6,PT-3DTKB,CCLF_SJ1002,BroadPanCancer2019,CCLF_SJ1002T_1_FM_SMGM_P9_2D_1,SM-OIKV6,...,Primary,CCLF_SJ1002T_1_FM_SMGM_P9_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Embryonal Rhabdomyosarcoma,FM/SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Parapharyngeal Space,CCLF
SM-OIKV7,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_AB1004,SM-OIKV7,PT-248NV,CCLF_AB1004,BroadPanCancer2019,CCLF_AB1004T_FM_OPAC_P16_2D_1,SM-OIKV7,...,Metastatic,CCLF_AB1004T_FM_OPAC_P16_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Esophogeal carcinoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,COHORT_AB,Liver,CCLF
SM-OIKV8,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_AB1052,SM-OIKV8,PT-29B72,CCLF_AB1052,BroadPanCancer2019,CCLF_AB1053T_ASC_FM_OPAC_P25_2D_1,SM-OIKV8,...,Metastatic,CCLF_AB1053T_ASC_FM_OPAC_P25_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Esophogeal carcinoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,COHORT_AB,Abdominal Cavity,CCLF
SM-OIKV9,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1048,SM-OIKV9,PT-3P1OV,CCLF_SJ1048,BroadPanCancer2019,CCLF_SJ1048T_1_FM_NPM_P9_2D_1,SM-OIKV9,...,Primary,CCLF_SJ1048T_1_FM_NPM_P9_2D_1,"Cells:Cell Line, Viable",DNA:DNA Somatic,Neuroblastoma,FM/NPM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Adrenal Gland,CCLF
SM-OIKVA,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_SJ1011,SM-OIKVA,PT-3DTKT,CCLF_SJ1011,BroadPanCancer2019,CCLF_SJ1020T_2_M87_SMGM_P15_2D_1,SM-OIKVA,...,Primary,CCLF_SJ1020T_2_M87_SMGM_P15_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Embryonal Rhabdomyosarcoma,M87/SMGM,Cancer Cell Line Factory (CCLF) / Michael Dyer...,COHORT_SJ,Prostate,CCLF
SM-OIKVB,gs://datarepo-37304743-bucket/48b21b72-1929-48...,gs://datarepo-37304743-bucket/48b21b72-1929-48...,CCLF_TWIST65,CCLF_RCRF1053,SM-OIKVB,PT-2CT34,CCLF_RCRF1053,BroadPanCancer2019,CCLF_cRCRF1001T_FM_OPAC_P12_2D_1,SM-OIKVB,...,Metastatic,CCLF_cRCRF1001T_FM_OPAC_P12_2D_1,Tissue:Fresh Tissue,DNA:DNA Somatic,Stomach Adenocarcinoma,FM/OPAC,Cancer Cell Line Factory (CCLF) / David Sandak...,COHORT_CCLF_RCRF,Abdominal Cavity,CCLF

# move bam/bai to terra bucket

In [38]:
from google.cloud import storage

def copy_file(bucket_name, blob_name, destination_bucket_name, destination_blob_name):
    """Copies a blob from one bucket to another with a new name."""
    storage_client = storage.Client()

    source_bucket = storage_client.bucket(bucket_name)
    source_blob = source_bucket.blob(blob_name)
    destination_bucket = storage_client.bucket(destination_bucket_name)

    new_blob = source_bucket.copy_blob(
        source_blob, destination_bucket, destination_blob_name
    )

    print(
        f"Blob {source_blob.name} in bucket {source_bucket.name} copied to "
        f"blob {new_blob.name} in bucket {destination_bucket.name}."
    )

In [39]:
for i in sample_info.index.tolist():
    for c in ['crai_or_bai_path', 'cram_or_bam_path']:
        full_fn = sample_info.loc[i, c]
        source_bucket_name = full_fn.split("/")[2]
        source_blob_name = "/".join(full_fn.split("/")[3:])
        destination_bucket_name = 'fc-ed07d172-7980-475e-81de-108a694a3532'
        destination_blob_name = samplesetnames[0] + '/' + full_fn.split("/")[-1]
        copy_file(source_bucket_name, source_blob_name, destination_bucket_name, destination_blob_name)
        new_fn = "gs://" + destination_bucket_name + "/" + destination_blob_name
        sample_info.loc[i, c] = new_fn

Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/08a29a02-d430-4331-8550-b01e0afa7ee5/CCLF_RCRF1003N_GL.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1003N_GL.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/41979d22-c505-4661-aa76-b1ab7ab6b83f/CCLF_RCRF1003N_GL.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1003N_GL.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/742a8441-9f33-457e-926b-b7123c48b0e2/CCLF_cRCRF1045N_GL.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_cRCRF1045N_GL.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/eb9ab218-f1be-4a03-9d01-cace73186720/CCLF_cRCRF1045N_GL.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_cRCRF1045N_GL.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/52d8a8e8-ff51-4a2e-baa3-9dcb591f2949/CCLF_cRCRF1066N_GL.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_cRCRF1066N_GL.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a4845a1a-1224-4a9d-bc7d-5219d736f759/CCLF_cRCRF1066N_GL.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_cRCRF1066N_GL.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/65c9f96b-43a8-4265-912d-bcacb6b23d53/CCLF_RCRF1060N.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1060N.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a78ed163-e2bd-4edb-91c0-39319a530eca/CCLF_RCRF1060N.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1060N.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/83532bd8-3dfa-4308-bb37-7d2833137cfd/CCLF_RCRF1180N.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1180N.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/40625952-2f95-4767-8f5d-3bc8fbe3ea4f/CCLF_RCRF1180N.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1180N.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/342b8100-9609-4c8e-aa3c-0b29259b68a4/CCLF_RCRF1189N.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1189N.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/beddf0ef-35a2-436a-bac8-dc2741c0aced/CCLF_RCRF1189N.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1189N.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/948f9fa1-e15f-4b8b-ac64-e44ce3358ac4/CCLF_RCRF1190N.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1190N.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a0671245-31a3-4305-8ac5-b54c6778ead5/CCLF_RCRF1190N.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_RCRF1190N.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/049d8db2-a094-4e1e-9fa2-8a0a37d15105/CCLF_NB1015N.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_NB1015N.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/0276d055-067d-4d2f-85ac-b91d70477d76/CCLF_NB1015N.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_NB1015N.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/e441b106-8763-410a-8380-49b659c3b1e1/CCLF_SJ1063T_2.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1063T_2.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/ef13fe2b-c373-42fd-881a-77a30dcf5773/CCLF_SJ1063T_2.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1063T_2.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/cf851403-594c-4ad0-b47b-d8d5cc80746d/CCLF_KL1089T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1089T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/80ac12c0-4704-452a-bc25-5ae1a9fd797a/CCLF_KL1089T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1089T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/873a3ced-06ab-4619-b84f-89917171b651/CCLF_GB1003T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1003T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/b70af2ea-c789-4409-bcee-207d37520e9f/CCLF_GB1003T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1003T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/11fc04bf-a4fa-4e0a-980c-73a326006e59/CCLF_SJ1006T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1006T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/b2173eb1-6460-497b-a82b-c9f12142ff55/CCLF_SJ1006T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1006T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/9f7cbe17-8308-4a77-957e-2f0b1af21b24/COL007T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/128a2d80-582a-4674-935c-20852fdf863a/COL007T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/5d130336-379b-47d7-8e17-091a09959a29/COL007T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/ee3879da-e3b6-4268-a9f3-22a3e099e8fd/COL007T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/4c8cfa98-1ad4-45f6-a361-d73ad4150567/AB053T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/AB053T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/6c7ea8e5-b52c-40c7-af49-6e0361800e3c/AB053T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/AB053T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/e13e8f8a-dea2-4625-8c66-4d7b55b45885/CCLF_SK1182T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1182T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/7b69e919-9eab-4e39-bbf6-07877d7e5658/CCLF_SK1182T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1182T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/0d15ab20-e794-4746-861c-28823de35bf7/CCLF_SK1183T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1183T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/9d59dcae-33d4-4cc2-ab89-f7f2ee58d16a/CCLF_SK1183T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1183T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a66304d6-66cb-448b-bca2-e366a6f14e1d/CCLF_SJ1010T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1010T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/01f4317e-c242-4ed6-9d22-0ff623a05444/CCLF_SJ1010T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1010T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/f376a9ff-27bf-4c25-9819-1d7c84f27c8c/CCLF_GB1008T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1008T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/d805e3d0-3aa5-43ed-a4fd-a14dc8dc14b3/CCLF_GB1008T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1008T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/1cc2375f-4207-491e-a651-df6a66044edd/COL007T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/684f3048-2d7d-4845-aa4c-c9ac7d1c7d53/COL007T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/66e47936-801e-460c-8fa6-334f327037dc/COL007T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/ef8c6c96-0d35-4707-903f-abc2d7897ada/COL007T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/COL007T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/da914bc0-1d40-40e3-a186-b2684d2a8c73/CCLF_KL1023T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1023T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/d3746db9-a876-4ca9-8e52-0de436bf0afa/CCLF_KL1023T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1023T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/abf0d769-8312-4a97-bc5c-c1de6fcb7f23/CCLF_KL1023T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1023T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/34558482-302c-41ed-bd0a-8276b17ed755/CCLF_KL1023T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1023T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a13e9346-dbce-47e6-a0eb-bc11b50bb324/CCLF_SK1183T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1183T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/bdd63791-bd17-49b9-a3d1-480e38997516/CCLF_SK1183T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1183T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/359602d1-df61-4a04-a9ec-1ac053073f05/CCLF_SJ1049T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1049T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/acbdc8ff-5b66-4672-80c6-bd69a12064a9/CCLF_SJ1049T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1049T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/34932f7e-52a1-47ab-8b40-76e2d1dd1e63/CCLF_AB1090T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1090T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/c0615a21-cf90-470e-8841-aa952d45c142/CCLF_AB1090T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1090T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/51e059d7-2b35-4896-88d8-5fe2be7dca8e/CCLF_SJ1004T_2.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1004T_2.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/6e5d1a22-0dd5-4283-abe5-0752a1a031c1/CCLF_SJ1004T_2.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1004T_2.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/703c4c3b-d9b5-458c-9354-3ff7f751e56e/CCLF_MDA1135T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_MDA1135T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/d572e31f-8cc4-4b85-a584-8b5e806e0524/CCLF_MDA1135T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_MDA1135T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/b90d02f7-1b77-4bb8-b81c-337425332c71/BT921.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/BT921.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/e63241c4-c2ed-4cd6-a801-d617d50e1b3d/BT921.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/BT921.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/43d0e39f-686b-4b48-a830-fadef46720ec/CCLF_AB1168T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1168T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/1e73a578-70a6-47b9-8ed7-d5857850a345/CCLF_AB1168T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1168T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/2d1d58a5-de68-4dc0-97ab-1850a0174feb/CCLF_SJ1009T_2.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1009T_2.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/c24dc9b7-6ebf-45ea-b1dc-8c4378ee0866/CCLF_SJ1009T_2.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1009T_2.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/9b0b3a0b-2898-4380-832f-54393d605449/CCLF_GB1004T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1004T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/b13c70b3-41aa-4a9d-83dd-f80f04814afd/CCLF_GB1004T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_GB1004T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/2b1b1b53-8b39-4169-b34c-d44758763dc2/CCLF_SJ1067T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/5bbb1275-a7e7-42c9-bb8c-4af890db66bc/CCLF_SJ1067T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/664ec3e4-00be-4747-a89f-74a90d8cd783/CCLF_KL1338T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1338T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/129d272b-b9ec-430b-af19-a3e94f7c374c/CCLF_KL1338T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_KL1338T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/945d59aa-1ed8-4476-903b-70847112cccf/CCLF_MDA1031T_AR5.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_MDA1031T_AR5.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/b7fce3bc-45ca-429c-b69c-5594756138c6/CCLF_MDA1031T_AR5.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_MDA1031T_AR5.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/3cd3bccc-9e57-404d-9323-d9baf03f008d/CCLF_SJ1037T_2.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1037T_2.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/ab28d964-2e03-4c75-aef5-dd55f9e6cca5/CCLF_SJ1037T_2.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1037T_2.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/f92efa11-a528-417c-9a3c-6d8d30a3e900/CCLF_PEDS1113T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_PEDS1113T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/0dc0712f-1d96-443b-8bea-53f330094dc9/CCLF_PEDS1113T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_PEDS1113T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/3777a239-6f2d-4160-bbab-507195913e00/CCLF_SK1176T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1176T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/dd74b2e5-2fff-48c7-9997-52ec6b50ee60/CCLF_SK1176T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1176T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/a2f50013-d246-48c0-a5fb-3c2e32e8e054/CCLF_SK1176T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1176T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/6dd1d814-73dd-4086-ba79-a089a933253c/CCLF_SK1176T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SK1176T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/78c6a0d4-d530-4195-83a1-ec2d907346f4/CCLF_SJ1067T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/3f6de2d8-0b3b-4f43-9219-5dcee58f033b/CCLF_SJ1067T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/17e96ffa-9fdc-409b-9ad4-9695a609edf5/CCLF_SJ1067T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/859d1fed-2064-44aa-8095-cfab62220a2d/CCLF_SJ1067T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1067T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/393b79ee-293c-42a2-8993-84e7289bb31f/CCLF_SJ1002T_1.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1002T_1.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/4e473d12-c4df-427d-afb4-dd94f13a9ba2/CCLF_SJ1002T_1.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_SJ1002T_1.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/11ababa4-d561-44da-ae33-ddcf55df98d7/CCLF_AB1004T.bam.bai in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1004T.bam.bai in bucket fc-ed07d172-7980-475e-81de-108a694a3532.
Blob 48b21b72-1929-48f0-b9a7-dc78d251ae88/e8f35207-abc4-4317-ab76-4a0268eaf8c6/CCLF_AB1004T.bam in bucket datarepo-37304743-bucket copied to blob CCLF_TWIST65/CCLF_AB1004T.bam in bucket fc-ed07d172-7980-475e-81de-108a694a3532.

In [40]:
filepath = 'data/sample_infos/%s_sample_info_transferred.tsv' % '_'.join(samplesetnames)
sample_info.to_csv(filepath, sep='\t')

# Creating the pairs
Create a TSV of the new pairs information.

In [42]:
newpairs = create_pairs_table(sample_info, wto)

creating new pairs...
Done

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:304: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  for tumor_id in sample_info[sample_info['participant'] == val][sample_info[

# Uploading samples and pairs to Terra

In [43]:
print("uploading new samples...")
wto.upload_samples(sample_info)
if not "NA" in wto.get_samples().index.tolist():
    wto.upload_samples(pd.DataFrame({'sample_id':['NA'], 'participant_id':['NA']}).set_index('sample_id'))
    wto.upload_samples(sample_info)

uploading new samples...
Successfully imported 39 participants.
Successfully imported 47 samples.

In [44]:
print("uploading pairs...")
wto.upload_entities('pair', newpairs)

uploading pairs...
Successfully imported 39 pairs.

# Create pair sets and sample sets

In the following cell, we create:
- a pair set for each batch
- sample sets for each batch 
- sample sets for each cohort

And then we upload these entities to the Terra workspace.

In [45]:
# Create pairs per batch dictionary
dict_pairs_per_batch = create_dict_of_pairs_per_sampleset(newpairs, sample_info, samplesetnames, save=True)

# Load from saved file
dict_pairs_per_batch = np.load('dict_pairs_per_batch.npy',allow_pickle='TRUE').item()

Saving dictionary of pairs per sampleset to dict_pairs_per_batch.npy

In [46]:
#  functionalized version
create_sample_sets_per_batch(sample_info, samplesetnames, samplesetnames_all, samplesetnames_tumors, samplesetnames_normals, proc_workspace)

create_pair_sets_per_batch(samplesetnames, samplesetnames_pairs, proc_workspace, dict_pairs_per_batch)

create_samplesets_and_pairsets_per_cohort(sample_info, samplesetnames, proc_workspace, cohorts2id, newpairs)

# get a list of all normals in the processing workspace
# TODO: I think by this point in the pipeline all of the samples will have been uploaded to Terra. Thus, I think we may only need the following one-liner to get a list of all normals:
# all_normals = [i for i, r in wto.get_samples().iterrows() if r['sample_type'] == "Normal"]

normalsid = [i for i, r in sample_info.iterrows() if r['sample_type'] == "Normal"]
print(len(normalsid))

refsamples = wto.get_samples()
normalsid.extend([k for k, _ in refsamples.iterrows() if _.sample_type == "Normal"])
print(len(normalsid))

create_aggregate_samplesets(normalsid, proc_workspace, wto)

Creating and uploading sample sets for each batch...
The sample set CCLF_TWIST65_all did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * CCLF_TWIST65_all (47 samples)
The sample set CCLF_TWIST65_tumors did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * CCLF_TWIST65_tumors (39 samples)
The sample set CCLF_TWIST65_normals did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * CCLF_TWIST65_normals (8 samples)
Uploading a pair set for each batch...
The pair set CCLF_TWIST65_pairs did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * CCLF_TWIST65_pairs (39 pairs)
Creating and uploading pairsets and samplesets by cohort (iterating over each batch)...

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_AB did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_AB (5 samples)
The pair set COHORT_AB did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_AB (5 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_BT did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_BT (5 samples)
The pair set COHORT_BT did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_BT (5 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_PEDS did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_PEDS (1 samples)
The pair set COHORT_PEDS did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_PEDS (1 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_NB did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_NB (1 samples)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_CCLF_RCRF did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_CCLF_RCRF (8 samples)
The pair set COHORT_CCLF_RCRF did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_CCLF_RCRF (1 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_COLO did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_COLO (4 samples)
The pair set COHORT_COLO did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_COLO (4 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

Sample set "COHORT_CCLF_RCRF" (8 samples) successfully updated.
Pair set "COHORT_CCLF_RCRF" (1 pairs) successfully updated.

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_SK did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_SK (5 samples)
The pair set COHORT_SK did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_SK (5 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_MDA did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_MDA (2 samples)
The pair set COHORT_MDA did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_MDA (2 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_SJ did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_SJ (13 samples)
The pair set COHORT_SJ did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_SJ (13 pairs)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:425: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

The sample set COHORT_GB did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * COHORT_GB (3 samples)
The pair set COHORT_GB did not exist in the workspace. Will be created now...
Successfully imported 1 pair sets:
  * COHORT_GB (3 pairs)
8
533
Creating and uploading sample sets for all samples in workspace, and all normals in workspace...
The sample set All_normals_TWIST did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * All_normals_TWIST (525 samples)
The sample set All_samples_TWIST did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * All_samples_TWIST (3048 samples)

***
***
# Push to Git repo (CCLF_TWIST) now!
This way, other people can easily take over the process of running the pipelines and feel confident that they have the most up-to-date version of this Jupyter notebook.
***
***

# Running Terra Worlflows
Run Terra workflows to get copy number (CNV) and mutation (SNV) information, and to create copy number heat maps by batch and by cohort.

The order of running the workflows is as follows:
- RenameBAM_TWIST
- CalculateTargetCoverage_PANCAN, 
    + DepthOfCov_PANCAN
- CreatePanelOfNormalsGATK_PANCAN, (edit the output config "normals_pon attribute"))
    + DepthOfCovQC_PANCAN
- CallSomaticCNV_PANCAN (edit the input config to match the output from CreatePanelOfNormalsGATK_PANCAN)
- PlotSomaticCNVMaps_PANCAN: we plot CN heat maps for each batch and also for each cohort
- MutationCalling_Normals_TWIST
- FilterGermlineVariants_NormalSample_TWIST
(edit the "PoN_name" config for CreatePoNSNV_Mutect1 and CreatePoNSNV_Mutect2)
- CreatePoNSNV_Mutect1, 
    + CreatePoNSNV_Mutect2
- SNV_PostProcessing_Normals, 
    + MutationCalling_Tumors_TWIST (edit the input config to match pon_mutect1, pon_mutect2)
- FilterGermlineEvents_TumorSample
- SNVPostProcessing_TWIST, 
    + FNG_Compile_Pileup_Cnt
- FNG_Compile_db_slow_download
- **do manual step here on local machine: need to merge two fingerprinting tables**
- FNG_Query_db

More information about the pipeline exist here: https://cclf.gitbook.io/tsca/

**Note 1:** If for som reason, one of the terra submission function gives no output and it does not seem to submit anything to terra, it might be that you have been logged out of terra you will have to reload the workspace manager and package.

**Note 2:** If you get the preflight error "expression and etype must BOTH be None or a string value", check the workflow configuration using wto.get_config("NAME_OF_WORKFLOW"). This error usually occurs when you pass in expression and etype information, but the etype is already set as the "rootEntity" aka the default for the workflow. You can fix this by either changing the workflow configuration in Terra, or by not passing in the etype or expression. If you want to see why this error occurs, look at the preflight function in lapdog.py (https://github.com/broadinstitute/lapdog/blob/master/lapdog/lapdog.py).

In [47]:
import time

def createManySubmissions(
    workspace, workflow, references, entity=None, expression=None, use_callcache=True
):
    """
    wrapper to create many submissions for a workflow

    Args:
    ----
      workspace: str namespace/workspace from url typically
      references: list(str) a list of name of the row in this entity
      entity: str terra csv type (sample_id...)
      expresson: str to use if want to compute on the direct value of the entity or on values of values
                  e.g. this.samples
      use_callcache: Bool to false if want to recompute everything even if same input

    Returns:
    ------
      submission_ids list(str) the submission ids
    """
    wm = dm.WorkspaceManager(workspace)
    submission_ids = []
    for ref in references:
        submission_ids += [
            wm.create_submission(workflow, ref, entity, expression, use_callcache)
        ]
    return submission_ids


def waitForSubmission(workspace, submissions, raise_errors=True):
    """
    wrapper to create many submissions for a workflow

    Args:
    -----
      workspace: str namespace/workspace from url typically
      submissions: list[str] of submission ids
      raise_errors: bool to true if errors should stop your code

    Returns:
    -------
      list of ids of failed submissions
    """
    failed_submission = []
    timing = 0
    wm = dm.WorkspaceManager(workspace).disable_hound()
    assert submissions is not None
    if type(submissions) is type(""):
        submissions = [submissions]
    for scount, submission_id in enumerate(submissions):
        finished = False
        while not finished:
            done = 0
            failed = 0
            finished = True
            submission = wm.get_submission(submission_id)["workflows"]
            for _, i in enumerate(submission):
                if i["status"] not in {"Done", "Aborted", "Failed", "Succeeded"}:
                    finished = False
                elif i["status"] in {"Failed", "Aborted"}:
                    failed += 1
                    if i["workflowEntity"]["entityName"] not in failed_submission:
                        print(i["workflowEntity"]["entityName"])
                        failed_submission.append(i["workflowEntity"]["entityName"])
                elif i["status"] in {"Done", "Succeeded"}:
                    done += 1
            if not finished:
                time.sleep(40)
                print(
                    "status is: Done for "
                    + str(done)
                    + " jobs in submission "
                    + str(scount)
                    + ". "
                    + str(timing)
                    + ",5 mn elapsed.",
                    end="\r",
                )
                timing += 1
                time.sleep(20)
                print(
                    "status is: Failed for "
                    + str(failed)
                    + " jobs in submission "
                    + str(scount)
                    + ". "
                    + str(timing)
                    + " mn elapsed.",
                    end="\r",
                )
            else:
                print(
                    str(done / (done + failed))
                    + " of jobs Succeeded in submission "
                    + str(scount)
                    + "."
                )
    if len(failed_submission) > 0 and raise_errors:
        raise RuntimeError(str(len(failed_submission)) + " failed submission")
    return failed_submission

In [48]:
print("Creating Terra submissions: remember you can only cancel \n or interact with terra submissions from the Terra website. \n https://app.terra.bio/#workspaces/"+proc_workspace.replace(" ", "%20")+"/job_history")

RenameBAM_TWIST = createManySubmissions(proc_workspace, "RenameBAM_TWIST", samplesetnames_all, 
                                              entity='sample_set', expression='this.samples')

print("waiting for 'Rename'")
waitForSubmission(proc_workspace, RenameBAM_TWIST)

Creating Terra submissions: remember you can only cancel
 or interact with terra submissions from the Terra website.
 https://app.terra.bio/#workspaces/nci-mimoun-bi-org/PANCAN_TWIST%20copy/job_history
Successfully created submission f18c3057-4207-4b2a-b677-f271d12601fe.
waiting for 'Rename'
1.0 of jobs Succeeded in submission 0.sion 0. 8 mn elapsed..

[]

In [49]:
waitForSubmission(proc_workspace, RenameBAM_TWIST)

1.0 of jobs Succeeded in submission 0.

[]

In [51]:
CalculateTargetCoverage_PANCAN = createManySubmissions(proc_workspace, "CalculateTargetCoverage_PANCAN", samplesetnames_all, 
                                              entity='sample_set', expression='this.samples')
DepthOfCov_PANCAN = createManySubmissions(proc_workspace, "DepthOfCov_PANCAN", samplesetnames_all, 
                                              entity='sample_set', expression='this.samples')

print("waiting for 'CalculateTargetCoverage' & 'DepthOfCov_PANCAN'")
combined_list = CalculateTargetCoverage_PANCAN + DepthOfCov_PANCAN
waitForSubmission(proc_workspace, combined_list)

Successfully created submission 6908e448-9798-4cd0-a0f6-d61cb6a97158.
Successfully created submission 3f618695-9ec1-482c-8544-d43978afc1b0.
waiting for 'CalculateTargetCoverage' & 'DepthOfCov_PANCAN'
SM-N1LYIs: Failed for 36 jobs in submission 0. 4 mn elapsed.
SM-OHWXY
SM-OHWY2
SM-OHWY9
SM-OHWYA
SM-OHWYC
SM-OHWYI
SM-OIKUR
SM-OIKV1
SM-OIKV5
SM-OIKV9
0.0 of jobs Succeeded in submission 0.
1.0 of jobs Succeeded in submission 1.sion 1. 17 mn elapsed..

RuntimeError: 47 failed submission

In [52]:
## Updates the config for each batch id
CreatePanelOfNormalsGATK_PANCAN = []
DepthOfCovQC_PANCAN = []
for ind, batch_id in enumerate(samplesetnames):
    # get current config for workflow that creates the PON for CNV calling
    createPON_config = wto.get_config('CreatePanelOfNormalsGATK_PANCAN')
    # edit the config
    createPON_config['outputs']['CreatePanelOfNormals.combined_normals'] = 'workspace.combined_normals_' + batch_id
    createPON_config['outputs']['CreatePanelOfNormals.normals_pon'] = 'workspace.pon_normals_' + batch_id
    createPON_config['outputs']
    # update the config in Terra
    wto.update_config(createPON_config)
    
    # create batch-specific PON to be used for CNVs
    CreatePanelOfNormalsGATK_PANCAN.append(wto.create_submission("CreatePanelOfNormalsGATK_PANCAN", samplesetnames_normals[ind]))
    DepthOfCovQC_PANCAN.append(wto.create_submission("DepthOfCovQC_PANCAN", samplesetnames_all[ind], etype='sample_set', expression='this.samples'))

Successfully updated configuration nci-mimoun-bi-org/CreatePanelOfNormalsGATK_PANCAN
Successfully created submission 530d26da-1065-484b-b138-2edbdbdd5cf4.
Successfully created submission 77ed6b8c-317c-4b1d-b370-00d1d2697c2b.

In [53]:
print("waiting for 'DepthOfCovQC_PANCAN' & 'CNV_CreatePoNForCNV'")
combined_list = DepthOfCovQC_PANCAN + CreatePanelOfNormalsGATK_PANCAN
waitForSubmission(proc_workspace, combined_list)

waiting for 'DepthOfCovQC_PANCAN' & 'CNV_CreatePoNForCNV'
1.0 of jobs Succeeded in submission 0.sion 0. 6 mn elapsed..
1.0 of jobs Succeeded in submission 1.

[]

In [54]:
CallSomaticCNV_PANCAN = []
for ind, batch_id in enumerate(samplesetnames):
    # get current config
    CNV_config = wto.get_config('CallSomaticCNV_PANCAN')
    CNV_config['inputs']['CallSomaticCNV.normals_pon']

    # edit the config
    CNV_config['inputs']['CallSomaticCNV.normals_pon'] = 'workspace.pon_normals_' + batch_id
    CNV_config['inputs']

    # update the config in Terra
    wto.update_config(CNV_config)
    CallSomaticCNV_PANCAN.append(wto.create_submission("CallSomaticCNV_PANCAN", samplesetnames_all[ind], etype='sample_set', expression='this.samples', use_callcache = True))

Successfully updated configuration nci-mimoun-bi-org/CallSomaticCNV_PANCAN
Successfully created submission b4911954-a6dc-43aa-b4c2-1bd1580e6d3c.

In [55]:
print("waiting for 'CallSomaticCNV_PANCAN'")
waitForSubmission(proc_workspace, CallSomaticCNV_PANCAN)

waiting for 'CallSomaticCNV_PANCAN'
1.0 of jobs Succeeded in submission 0.sion 0. 10 mn elapsed.

[]

In [56]:
# in case you want to rerun the notebook and generate the sample key variables
sample_info, all_pairsets, cohorts_per_batch, cohort_pairsets, all_changed_cohorts = \
    regenerate_variables(wto, samplesetnames_all, cohorts2id)

/home/ubuntu/projects/CCLF_TWIST/src/helper.py:54: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tumorsamplesincohort = batch_sample_info[batch_sample_info["cohorts"] == val][batch_sample_info['sample_type']=="Tumor"].index.tolist()

In [57]:
cohort_pairsets

{'COHORT_AB',
 'COHORT_BT',
 'COHORT_CCLF_RCRF',
 'COHORT_COLO',
 'COHORT_GB',
 'COHORT_MDA',
 'COHORT_NB',
 'COHORT_PEDS',
 'COHORT_SJ',
 'COHORT_SK'}

In [58]:
sample_info

,Collection,aggregation_product_name_validation,batch,bsp_sample_id_validation,clear_snvs,cnv_calls,cohorts,crai_or_bai_path,cram_or_bam_path,depth_of_cov_qc_result,...,source_subtype_validation,squid_sample_id_validation,stock_sample_id_validation,target_coverage,tissue_site,tumor_ptn,tumor_seg,tumor_seg_for_plotting,tumor_subtype,tumor_tn
sample_id,,,,,,,,,,,,,,,,,,,,,
NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SM-IF6GG,Cancer Cell Line Factory (CCLF) / Charles Yoon...,Pancan_396_NO_INTRONS,CCLF_TWIST1,SM-IF6GG,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,COHORT_CY,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,pass,...,Tissue:Fresh Tissue,CCLF_CY1001T_RETM_p5_2D_1,SM-HUTA4,gs://fc-ed07d172-7980-475e-81de-108a694a3532/0...,Soft tissue,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...
SM-IF6GH,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,Pancan_396_NO_INTRONS,CCLF_TWIST1,SM-IF6GH,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,COHORT_BT,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,pass,...,"Cells:Cell Line, Viable",CCLF_KL1187T_CM_p7_2D_1,SM-HSBF9,gs://fc-ed07d172-7980-475e-81de-108a694a3532/0...,Brain,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...
SM-IF6GI,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,Pancan_396_NO_INTRONS,CCLF_TWIST1,SM-IF6GI,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,COHORT_BT,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,pass,...,"Cells:Cell Line, Viable",CCLF_KL1212T_NSA_p5_Laminin_1,SM-HSBFG,gs://fc-ed07d172-7980-475e-81de-108a694a3532/0...,Brain,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,Primary,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...
SM-IF6GJ,Cancer Cell Line Factory (CCLF) / Keith Ligon ...,Pancan_396_NO_INTRONS,CCLF_TWIST1,SM-IF6GJ,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,COHORT_BT,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,gs://fc-51648132-739d-4b71-9800-03fb9f9990c6/C...,pass,...,Tissue:Fresh Tissue,CCLF_KL1205T_SMGM_p7_2D_1,SM-HSBF3,gs://fc-ed07d172-7980-475e-81de-108a694a3532/0...,Brain,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SM-OIKV7,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,BroadPanCancer2019,CCLF_TWIST65,SM-OIKV7,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,COHORT_AB,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,pass,...,Tissue:Fresh Tissue,CCLF_AB1004T_FM_OPAC_P16_2D_1,SM-OIKV7,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Liver,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...
SM-OIKV8,Cancer Cell Line Factory (CCLF) / Adam Bass/Ku...,BroadPanCancer2019,CCLF_TWIST65,SM-OIKV8,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,COHORT_AB,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,pass,...,Tissue:Fresh Tissue,CCLF_AB1053T_ASC_FM_OPAC_P25_2D_1,SM-OIKV8,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Abdominal Cavity,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...
SM-OIKV9,Cancer Cell Line Factory (CCLF) / Michael Dyer...,BroadPanCancer2019,CCLF_TWIST65,SM-OIKV9,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,COHORT_SJ,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,pass,...,"Cells:Cell Line, Viable",CCLF_SJ1048T_1_FM_NPM_P9_2D_1,SM-OIKV9,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Adrenal Gland,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Primary,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...
SM-OIKVA,Cancer Cell Line Factory (CCLF) / Michael Dyer...,BroadPanCancer2019,CCLF_TWIST65,SM-OIKVA,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,COHORT_SJ,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,pass,...,Tissue:Fresh Tissue,CCLF_SJ1020T_2_M87_SMGM_P15_2D_1,SM-OIKVA,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Prostate,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Primary,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...
SM-OIKVB,Cancer Cell Line Factory (CCLF) / David Sandak...,BroadPanCancer2019,CCLF_TWIST65,SM-OIKVB,NaN,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,COHORT_CCLF_RCRF,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/C...,pass,...,Tissue:Fresh Tissue,CCLF_cRCRF1001T_FM_OPAC_P12_2D_1,SM-OIKVB,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Abdominal Cavity,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...,Metastatic,gs://fc-ed07d172-7980-475e-81de-108a694a3532/s...

In [59]:
# create CNV map for each batch
createManySubmissions(proc_workspace, "PlotSomaticCNVMaps_PANCAN", samplesetnames_all, use_callcache = False)
# create CNV map for each cohort
createManySubmissions(proc_workspace, "PlotSomaticCNVMaps_PANCAN", list(all_changed_cohorts), use_callcache = False)

print("submitted final jobs for CNV pipeline")
print("you don't need to wait before moving onto the next cell")

Successfully created submission 37427256-fbba-4609-a74a-756b947b458f.
Successfully created submission 0eb4b7aa-87b0-496d-869f-710b43f7e931.
Successfully created submission 8dc818ee-8c5e-43f5-a816-3143022dce35.
Successfully created submission 60044b9b-e4d2-4d07-be24-b661958334a4.
Successfully created submission 89c3d7b0-24a1-478d-ae90-6882a8d0d7d4.
Successfully created submission 9336ae8f-64a5-4918-898f-9937f601f684.
Successfully created submission 880332de-43ea-4efa-85bf-f016ac04530c.
Successfully created submission 460af2d8-c38d-41d9-aa1b-b0dc90041025.
Successfully created submission 61af72fc-4a34-4363-b9c9-cef40ecd3180.
Successfully created submission e1a6f13e-476a-47ec-974f-536925d21222.
Successfully created submission f0b57612-ab77-4dfd-b6f5-33b1465decd4.
submitted final jobs for CNV pipeline
you don't need to wait before moving onto the next cell

In [ ]:
MutationCalling_Normals_TWIST = createManySubmissions(proc_workspace, "MutationCalling_Normals_TWIST", samplesetnames_normals, 
                                              entity='sample_set', expression='this.samples')
print("waiting for 'MutationCalling_Normals_TWIST'")
waitForSubmission(proc_workspace, MutationCalling_Normals_TWIST)

status is: Failed for 0 jobs in submission 0. 1 mn elapsed.

In [62]:
FilterGermlineVariants_NormalSample_TWIST = createManySubmissions(proc_workspace, "FilterGermlineVariants_NormalSample_TWIST", samplesetnames_normals, 
                                              entity='sample_set', expression='this.samples', use_callcache=True)
print("waiting for 'SNV_FilterGermline'")
waitForSubmission(proc_workspace, FilterGermlineVariants_NormalSample_TWIST)

Successfully created submission d78103c4-a7bd-4b5c-8705-c4ebfc02f23d.
waiting for 'SNV_FilterGermline'
1.0 of jobs Succeeded in submission 0.sion 0. 5 mn elapsed.

[]

In [63]:
# get current config
mutect1_config = wto.get_config('CreatePoNSNV_Mutect1')
mutect2_config = wto.get_config('CreatePoN_SNV_MuTect2')

# edit the config
mutect1_config['inputs']['CreatePanelOfNormals.PoN_name'] = '"Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect1"'
mutect2_config['inputs']['CreatePanelOfNormals.PoN_name'] = '"Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect2"'
mutect1_config['outputs']['CreatePanelOfNormals.normals_pon_vcf'] = 'workspace.Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect1'
mutect2_config['outputs']['CreatePanelOfNormals.createPanelOfNormals.normals_pon_vcf'] = 'workspace.Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect2'

# update the config in Terra
wto.update_config(mutect1_config)
wto.update_config(mutect2_config)

# create PON for SNV from all the normals we have in the workspace so far
CreatePoNSNV_Mutect1 = wto.create_submission('CreatePoNSNV_Mutect1', "All_normals_TWIST")
CreatePoN_SNV_MuTect2 = wto.create_submission('CreatePoN_SNV_MuTect2', "All_normals_TWIST")

Successfully updated configuration nci-mimoun-bi-org/CreatePoNSNV_Mutect1
Successfully updated configuration nci-mimoun-bi-org/CreatePoN_SNV_MuTect2
Successfully created submission e249994d-f3b8-41b0-8b72-58f6217d4c1c.
Successfully created submission 599246a6-e81b-4bd4-9192-dd5073de4ab7.

In [64]:
print("waiting for 'CreatePoN_SNV_MuTect2' & 'CreatePoNSNV_Mutect1'")
waitForSubmission(proc_workspace, [CreatePoNSNV_Mutect1, CreatePoN_SNV_MuTect2])

waiting for 'CreatePoN_SNV_MuTect2' & 'CreatePoNSNV_Mutect1'
1.0 of jobs Succeeded in submission 0.sion 0. 30 mn elapsed.
1.0 of jobs Succeeded in submission 1.

[]

## Note: It may be okay if some samples fail the MutationCalling_Tumors_TWIST workflow. Samples will fail if no mutations made it through Mutect1 and Mutect2's filters.
The MutationCalling_Tumors_TWIST pipeline has been updated to use GATK4, and there are many more pre-filters for Mutect2 that greatly reduce the computation time required. As part of this change, however, we discovered that the next step (FilterMutectCalls) will fail if the vcf it gets from Mutect2 is empty. This can happen if all the variants are filtered out. Thus, long story short, if the sample fails at the FilterMutectCalls step and the log file shows that there were no variants left after Mutect1 and Mutect2, then this failure is not something to worry about.

The details can be found at https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2 by searching for "Read filters". In addition to the prefilters described in that section, Mutect2 also prefilters sites that are in the matched normal and the PoN.

In [65]:
SNV_PostProcessing_Normals = []
MutationCalling_Tumors_TWIST = []
for ind, batch_id in enumerate(samplesetnames):
    
    # get config 
    mutcall_tumor = wto.get_config('MutationCalling_Tumors_TWIST')

    # edit the config
    mutcall_tumor['inputs']['MutationCalling_Tumor.pon_mutect1'] = 'workspace.Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect1'
    mutcall_tumor['inputs']['MutationCalling_Tumor.pon_mutect2'] = 'workspace.Cum_PoN_' + samplesetnames[-1] + '_all_vcf_mutect2'
    
    # check config
    print(mutcall_tumor['inputs']['MutationCalling_Tumor.pon_mutect1'])
    print(mutcall_tumor['inputs']['MutationCalling_Tumor.pon_mutect2'])
    
    # update the config in Terra
    wto.update_config(mutcall_tumor)

    # create submission
    SNV_PostProcessing_Normals += [wto.create_submission("SNV_PostProcessing_Normals", samplesetnames_normals[ind])]
    
    MutationCalling_Tumors_TWIST += [wto.create_submission("MutationCalling_Tumors_TWIST", samplesetnames_pairs[ind], etype='pair_set', expression='this.pairs')]

workspace.Cum_PoN_CCLF_TWIST65_all_vcf_mutect1
workspace.Cum_PoN_CCLF_TWIST65_all_vcf_mutect2
Successfully updated configuration nci-mimoun-bi-org/MutationCalling_Tumors_TWIST
Successfully created submission cea1a21d-1131-48ea-83a7-8d016329fd0d.
Successfully created submission d960ce3c-6038-493e-b20f-237c5ef4bdff.

In [66]:
print("waiting for 'SNV_PostProcessing_Normals' & 'MutationCalling_Tumors_TWIST'")
combined_list = SNV_PostProcessing_Normals + MutationCalling_Tumors_TWIST
waitForSubmission(proc_workspace, combined_list)

waiting for 'SNV_PostProcessing_Normals' & 'MutationCalling_Tumors_TWIST'
1.0 of jobs Succeeded in submission 0.sion 0. 5 mn elapsed.
1.0 of jobs Succeeded in submission 1.sion 1. 229 mn elapsed..

[]

In [67]:
## note: you might see that some of the cohorts fail on this workflow. That can be expected: the workflow needs cohorts with at least 2 acceptable cell lines to run (if only 1, then the workflow will fail)
FilterGermlineEvents_TumorSample = createManySubmissions(proc_workspace, 'FilterGermlineEvents_TumorSample', samplesetnames_pairs, 'pair_set', expression='this.pairs')
print("waiting for 'FilterGermlineEvents_TumorSample'")
waitForSubmission(proc_workspace, FilterGermlineEvents_TumorSample)

Successfully created submission b6ac9180-03fd-467c-8e28-26e9a69cd821.
waiting for 'FilterGermlineEvents_TumorSample'
1.0 of jobs Succeeded in submission 0.sion 0. 7 mn elapsed..

[]

In [68]:
# create aggregate SNV tsvs for each batch
createManySubmissions(proc_workspace, "SNVPostProcessing_TWIST", samplesetnames_pairs)
# create aggregate SNV tsvs for each cohort
createManySubmissions(proc_workspace, "SNVPostProcessing_TWIST", list(cohort_pairsets))
print("Submitted final jobs for SNV pipeline")

Successfully created submission 6139209f-601d-4022-8488-cd7989db63f3.
Successfully created submission 60b7e143-a03c-4287-8752-5cee7a74b06e.
Successfully created submission 863682f7-1c04-40e0-9884-031a96f7897b.
Successfully created submission 9ad062f7-3c8e-4505-abe1-9e299b7a4b22.
Successfully created submission 041e7e57-4c07-4fab-809f-498bcb2ebda7.
Successfully created submission 26a71f04-4e22-4c08-95fb-4fba37b65113.
Successfully created submission 6a8f517e-7fe7-482c-b86e-db8b4745148a.
Successfully created submission 1fe2df3a-f3ab-4222-b968-3987dc421165.
Successfully created submission bfb1a533-7f00-4bf5-80b7-d524c77547ce.
Successfully created submission b237de3b-2abc-4d48-92de-4d2776b8fc29.
Successfully created submission 1cc3869f-ed0d-445d-897e-276ed75b8afe.
Submitted final jobs for SNV pipeline

## Fingerprinting (FNG)

In [69]:
# determine the FNG pileup counts for each sample
FNG_Compile_Pileup_Cnt = createManySubmissions(proc_workspace, "FNG_Compile_Pileup_Cnt", samplesetnames_all, entity='sample_set', expression='this.samples')
print("waiting for 'FNG_Compile_Pileup_Cnt'")
waitForSubmission(proc_workspace, FNG_Compile_Pileup_Cnt)

Successfully created submission 8aaa53f9-f3a8-43b6-95e2-63cab9f36af4.
waiting for 'FNG_Compile_Pileup_Cnt'
1.0 of jobs Succeeded in submission 0.sion 0. 7 mn elapsed..

[]

In [71]:
# create the proper "super" set of samples to run through the FNG compiler
# if processing multiple batches at once, this will correspond to a sample "super" set containing the sample IDs from all the new batches. If processing a single batch, this will just be that batch's sample set.
samples_to_add = []
for set_name in samplesetnames_all:
#     samples_to_add += wto.get_sample_attributes_in_set(set_name).index.tolist()
    samples_to_add += wto.get_sample_sets().loc[set_name, 'samples']
samples_to_add
print(samples_to_add)

fng_sampleset_id = "_".join(samplesetnames)
print(fng_sampleset_id)

addToSampleSet(workspace = proc_workspace, samplesetid = fng_sampleset_id, samples = samples_to_add)

['SM-M1DNP', 'SM-OIKUP', 'SM-OHWYD', 'SM-OHWYI', 'SM-OIKV4', 'SM-OHWYG', 'SM-OIKUW', 'SM-OIKV2', 'SM-OIKUR', 'SM-OIKUV', 'SM-OIKVB', 'SM-NEJCO', 'SM-OIKV1', 'SM-OHWY5', 'SM-OHWY4', 'SM-OHWXZ', 'SM-OHWYC', 'SM-LYFLX', 'SM-OIKUS', 'SM-OIKV8', 'SM-OIKV9', 'SM-OHWY2', 'SM-OIKUT', 'SM-OHWYF', 'SM-OHWYB', 'SM-JKMLF', 'SM-N1LYJ', 'SM-OIKV3', 'SM-OHWYA', 'SM-OHWY9', 'SM-OHWYE', 'SM-JKMLH', 'SM-OHWXY', 'SM-OHWY3', 'SM-OHWY6', 'SM-JKMLG', 'SM-OIKV7', 'SM-OIKUU', 'SM-OIKUQ', 'SM-OIKUX', 'SM-OIKVA', 'SM-OIKUZ', 'SM-OHWY8', 'SM-OIKV5', 'SM-N1LYI', 'SM-OIKV6', 'SM-OIKUY']
CCLF_TWIST65
The sample set CCLF_TWIST65 did not exist in the workspace. Will be created now...
Successfully imported 1 sample sets:
  * CCLF_TWIST65 (47 samples)

In [72]:
## Update the output config to create the new FNG database
# get current config for the FNG compiling workflow
fngCompile_config = wto.get_config('FNG_Compile_db_slow_download')
# edit the config
# TODO: would be nice to be able to change the name of the outputted FNG database. Right now, all named the same.
# fngCompile_config['inputs']['FNG_Compile_db.compile_db.output_file_name'] = '"fingerprinting_db_through_' + samplesetnames[-1] + '.txt"'
fngCompile_config['outputs']['FNG_Compile_db.compile_db.fingerprinting_db'] = 'workspace.fingerprinting_db_through_' + samplesetnames[-1]
fngCompile_config['outputs']['FNG_Compile_db.compile_db.fingerprinting_db_current'] = 'workspace.fingerprinting_db'
fngCompile_config['outputs']

print(fngCompile_config)
# update the config in Terra
wto.update_config(fngCompile_config)

{'deleted': False, 'inputs': {'FNG_Compile_db.pileup_pct_count_files': 'this.samples.pileup_pct_count', 'FNG_Compile_db.prev_fng_db_path': 'workspace. fingerprinting_db', 'FNG_Compile_db.sample_ids': 'this.samples.sample_id', 'FNG_Compile_db.tsca_ids': 'this.samples.batch'}, 'methodConfigVersion': 81, 'methodRepoMethod': {'methodName': 'FNG_Compile_db_slow_download', 'methodVersion': 7, 'methodNamespace': 'nci-mimoun-bi-org', 'methodUri': 'agora://nci-mimoun-bi-org/FNG_Compile_db_slow_download/7', 'sourceRepo': 'agora'}, 'name': 'FNG_Compile_db_slow_download', 'namespace': 'nci-mimoun-bi-org', 'outputs': {'FNG_Compile_db.compile_db.fingerprinting_db': 'workspace.fingerprinting_db_through_CCLF_TWIST65', 'FNG_Compile_db.compile_db.fingerprinting_db_current': 'workspace.fingerprinting_db'}, 'prerequisites': {}, 'rootEntityType': 'sample_set'}
Successfully updated configuration nci-mimoun-bi-org/FNG_Compile_db_slow_download

In [75]:
# create FNG db using Method Version 7
# TODO: update method to change the output file name to something more descriptive
# pass in a sample set containing all of the new samples you're processing
# do not use call cache; we need to see if the github repo has been updated and thus must clone each time
FNG_Compile_db_slow_download = wto.create_submission("FNG_Compile_db_slow_download", fng_sampleset_id, use_callcache=False)
print("waiting for 'FNG_Compile_db'")
waitForSubmission(proc_workspace, FNG_Compile_db_slow_download)

Successfully created submission c7afcd29-78ca-4987-8654-e0bc05dc2d5b.
waiting for 'FNG_Compile_db'

KeyboardInterrupt:

### "FNG_Compile_db_slow_download" command is problematic currently
**NOTE**: The "FNG_Compile_db_slow_download" command is problematic currently in this workspace because this workspace only contains TWIST samples, but we want to be able to look at fingerprinting data from both TSCA and TWIST. Currently, Gwen merges the previous fingerprinting_db.txt file with the newly created fingerprinting_db.txt. We'll have to repeat this merging procedure unless we edit the workflow. Gwen has started this process, but hasn't finished the edits (just need to build the proper docker container). So for now (1/15/20), still need to do the merging locally (unfortunately).

See the R file: "src/FNG_TWIST_and_TSCA_merge" in the CCLF_TWIST GitHub repo.

### TODO: this is where the merging work in R needs to be performed on local.
See the R file: `CCLF_TWIST/src/FNG_TWIST_and_TSCA_merge.Rmd` in the CCLF_TWIST GitHub repo. 
-> The details of what you need to do are in this Rmd file.
-> Once the local work is done, continue running through the chunks below.

I also have the same merging script in `CCLF_TWIST/workflow/scripts/merge_fingerprinting_dfs.R`, and a WDL script to run this at `CCLF_TWIST/workflow/scripts/merge_fng_databases.wdl`. This has been uploaded to Terra, too, and I have made a workflow for this in the data processing workspace: "merge_FNGs". However, the Docker image is missing the Argparse package. I think once this is added to the Docker image, the workflow should run smoothly on Terra.

In [77]:
# 8/4/2021, Javad's efforts to implement the R code in the python cell
# This seems to be redundant though. For some reason, the binding of the
# data already has happened in the FNG_Compile_db_slow_download output
# This seems to at least be the case for TWIST35

import pandas as pd

workspace_attr = wto.get_workspace_metadata()['workspace']['attributes']
fp_old = pd.read_csv(workspace_attr['fingerprinting_db_through_CCLF_TWIST34'], sep='\t')
fp_new = pd.read_csv(workspace_attr['fingerprinting_db_through_' + samplesetnames[-1]], sep='\t')
assert not fp_new.duplicated().any()
assert not fp_old.duplicated().any()
assert set(fp_new.columns) == set(fp_old.columns)
assert (set(fp_old['batch']) - set(fp_new['batch'])) == set([])

# not sure why this is necessary. It produces identical results
fp_all = pd.concat([fp_new, fp_old])
fp_all.drop_duplicates(inplace=True)
fp_all.reset_index(drop=True, inplace=True)
assert fp_new.shape == fp_all.shape
assert fp_all.equals(fp_new)
fp_all.to_csv('/tmp/fingerprinting_db_through_{}.txt'.format(samplesetnames[-1]), sep='\t', index=False)

In [ ]:
# for each batch, query the FNG database
FNG_Query_db = createManySubmissions(proc_workspace, "FNG_Query_db", samplesetnames_all)
print("Submitted final FNG Job")
waitForSubmission(proc_workspace, FNG_Query_db)
print('Done')

Successfully created submission d7b7c379-39ed-4d99-87cb-9e98eec18a83.
Submitted final FNG Job
status is: Done for 0 jobs in submission 0. 0,5 mn elapsed.

# You've finished running through the pipeline!
You should have all the SNV, CNV, and FNG results ready in Terra. Update the Asana task.

<!-- # If got a new cohort label / abbreviation and need to update data that already exists in Terra: -->

In [ ]:
# # Get data from Gsheet metadata
# metadata = pd.concat(gsheets,sort=False, keys = samplesetnames)
# metadata = metadata.reset_index().rename(columns = {'level_0':'batch', "External ID":'external_id_validation'}).drop(['level_1'], axis = 'columns')
# metadata.index = metadata['Exported DNA SM-ID']

# display(metadata.head())

# # Pull relevant sample_info from Terra
# sample_info = wto.get_samples()
# sample_info = sample_info[sample_info["batch"].isin(samplesetnames)]
# display(sample_info.head())
# # display(sample_info.loc[:,["cohorts", "Collection"]])

# # Merge new Metadata with stuff existing in Terra (in particular, we often want to update the Collections and cohorts columns)
# updated = pd.concat([sample_info.drop(columns=['Collection']), metadata["Collection"].reindex(sample_info.index)], axis=1)
# updated.head()
# updated.columns.tolist()
# updated = updated.reindex(columns=(['Collection', 'cohorts'] + list([a for a in updated.columns if a not in ['Collection', 'cohorts']]) ))
# updated

# updated = getCohortAbbreviations(updated)
# updated
# print("Final 'updated' df, looking at just the cohorts and Collection columns:")
# display(updated.loc[:,["cohorts", "Collection"]].head())